sapcc/nova

nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
VT-X enabled on VMs with flavor-property "vmware:hv_enabled=true"
=> VTX-support on flag

nova/objects/migrate_data.py, nova/virt/driver.py, nova/virt/vmwareapi/cluster_util.py, nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/nova_vcenter_config_endpoint.py, nova/virt/vmwareapi/vcenter_rpc_client.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
This is currently limited to a single vcenter
=> vsphereapi: VMotion as a live migration between two host

nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/host.py
Report CPU on the ESXI hosts - merge from mitaka-m3
=> Merge /nova/pull/3 and nova/pull/6 pull requests from mitaka-m3

nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
Merging video ram validation from stable/mitaka-m3 - /nova/pull/14
=> Merging video ram from mitaka to queens

nova/compute/monitors/__init__.py, nova/compute/monitors/base.py, nova/compute/monitors/compute_node/vmware_monitor.py, nova/objects/fields.py, nova/virt/vmwareapi/driver.py, setup.cfg
Merge /nova/pull/15 "Storage monitor" from stable/mitaka-m3 to stable/queens-m3
=> VMware storage monitor merge from mitaka to queens

nova/virt/vmwareapi/vmops.py
=> [vmwareapi] Fix resizing of images - a5932a9a9d1fb8e87d93fb73562c46c843396637 id

nova/db/sqlalchemy/migrate_repo/versions/320_fix_quota_double_spending.py
…45cda1336db691cc1d011fd9a3c id
=> add a uniqueness constraint to the quota_usages table - b6490efe93ef645cda1336db691cc1d011fd9a3c id

nova/scheduler/filters/baremetal_exact_core_filter.py, nova/scheduler/filters/baremetal_exact_disk_filter.py, nova/scheduler/filters/baremetal_exact_ram_filter.py
=> Added BaremetalExact*Filters - 85b81244ed4198f551437c9a2227d7ff23b2a188 id

nova/compute/manager.py
This might solve #45.
The codes hasn't been even checked on syntax, so do not merge
=> Do not block on reservation

nova/api/openstack/common.py, nova/api/openstack/compute/limits.py, nova/api/openstack/compute/quota_classes.py, nova/api/openstack/compute/quota_sets.py, nova/api/openstack/compute/used_limits.py, nova/api/openstack/compute/views/limits.py, nova/cmd/api.py, nova/compute/api.py, nova/compute/utils.py, nova/db/api.py, nova/db/sqlalchemy/api.py, nova/objects/instance.py, nova/objects/quotas.py, nova/quota.py
This is mostly a straight-forward port of #16.
@fwiesel I have not tested this yet since we don't have a Nova DB anywhere with the required migrations yet. If you want to hold this PR back until I can test it in QA, that's fine by me.
~~WIP: I need to go through the `stable/mitaka-m3` branch for all those nitty-gritty fixes that I did after #16 was already merged.~~
=> baremetal quota handling, Queens edition

nova/virt/vmwareapi/vmops.py
As discussed with @notandy and @joker-official
=> disable image_as_template by default

nova/virt/vmwareapi/images.py
=> Removed repeatedly called methods in images.py fetch_image_stream_optimized

nova/bigvm/manager.py
In production we face slightly different sizes of hypervisors (we've
seen around 100 MB for 3 TB hosts). We need to handle all of them as
being the same size in the nova-bigvm service, as we don't want to keep
too many hosts freed up for basically the same size of bigVM.
We approach this, by creating buckets out of the hv_sizes, taking the
smallest one as bucket key, creating a new bucket every time the
difference between two hv_sizes is above a certain threshold. The
bucket-key is than used instead of the original hv_size for any further
decisions.
=> bigvm: Handle slightly different HV sizes

nova/bigvm/manager.py
We now check in every iteration, that a host we marked as free earlier
is still free. We do this by calling the `free_host()` method initially
used to free up the host, which should return FREE_HOST_STATE_DONE if
there are no VMs on that host anymore. If it returns anything else, we
know that the host is no longer free, delete the child resource-provider
and try to find a new resource-provider capable of holding a free host
for this size.
=> [bigvm] Constantly check that a host is still free

nova/cmd/manage.py
Collect active-instance ids from other cells (other than
cell0 and cell1) as well. These ids are passed to the purge
function to leave the respective request_specs and, more
importantly, instance_mappings alone when cleaning up.
Failure to do so will delete instance_mappings for instances
in these other cells.
=> Fix purge-request-specs manage cmd for multi-cell setups

nova/tests/unit/compute/test_rpcapi.py
Fixup commit 2581ec7889f6c127c3fcee6274d26ad5bfd5d10d which
introduced a timeout argument into the RPC client prepare()
call but didn't update the unit tests.
=> Fix tests with reserve_block_device_name timeout

nova/bigvm/manager.py
In Nova's rocky version, placement learned to handle nested providers in
a better way and supports them from version 1.29 on - which isn't in
rocky. Upstream thus added code to filter out nested providers from the
response. The problem with that is, that we modeled our
CUSTOM_BIGVM-providing resource providers as children of the
nova-compute-bb* provider. Therefore, our big VM spawning code cannot
find an allocation candidate anymore.
We now switch to created the "child" RPs as individual RPs instead. For
identifying their "parent", we now use the aggregate assigned to them.
Change-Id: Ic9d707c59a4ea405f3a982dbe269cdfea0d03aa5
=> bigvm: Create RPs without parent

nova/compute/api.py, nova/conf/scheduler.py, nova/scheduler/filters/resize_reservation_filter.py, nova/scheduler/utils.py, nova/tests/unit/compute/test_compute_api.py, nova/tests/unit/scheduler/filters/test_resize_reservation_filter.py
- Added new config to scheduler
'reserved_ram_threshold_for_resize' = 10.0
- Added tests simmilar to ram_filter
- Moved 'is_resize' to nova/utils.py
=> Added filter for reserving resources for resize

nova/tests/unit/virt/vmwareapi/test_vmops.py, nova/virt/vmwareapi/driver.py
There where two print statements in the code.
=> Vmware: Remove print statements

nova/network/neutronv2/api.py
In case we already created a binding for a live-migration
but crashed during the ongoing process, neutron will already
hold a port binding for the host.
Instead of failing, we can simply take the existing port-binding
and continue.
Possibly, also other port binding creations can profit from the behaviour.
=> Idempotent binding creation

nova/virt/vmwareapi/vm_util.py
All vm related api calls work with ManagedObject-References (morefs),
while openstack works with instance uuids.
In order to avoid having to call vsphere to map the instance uuid to such a moref,
the driver keeps a cache. The implementation assumes that those morefs are stable
However, the operator can unregister and reregister a VM, which would cause the moref to change.
Any operation on the previous moref would cause a ManagedObjectNotFoundException.
We retry function annotated with the decorator vm_ref_cache_heal_from_instance:
Removing a stale entry from the cache will either result now in recovering
a new moref or raising InstanceNotFound, which is properly handled
=> VMware: Try to recover from outdated vm-refs

.pre-commit-config.yaml
This way we stay more close the upstream also
in the development process
Change-Id: I51d9340205ddaa1266441347dac0c47ff05ec9f0
=> Add pre-commit-yaml from nova/master

nova/virt/vmwareapi/cluster_util.py, nova/virt/vmwareapi/vim_util.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
We need those functions to build the sync-loop for DRS rules and groups for when customers can change the server-groups via API.
=> VMware: Add functions to retrieve a cluster's DRS rules and groups

nova/compute/api.py, nova/compute/manager.py, nova/compute/rpcapi.py, nova/conf/vmware.py, nova/virt/driver.py, nova/virt/vmwareapi/cluster_util.py, nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/vmops.py
Please see the commit-messages for details.
I haven't taken care of the tests, yet, as I would like to get early feedback first.
=> vmware: Add a way to sync server-groups

nova/virt/vmwareapi/special_spawning.py
Those came up as a problem in production recently and are easily fixable.
=> small special spawning fixes/improvements

nova/compute/resource_tracker.py, nova/tests/unit/compute/test_resource_tracker.py
The resource tracker iterates over all instances in
_update_usage_from_instances, where it will the fetch
for each instance the block-device-mappings in an rpc call.
By fetching the block-device-mappings up-front,
we get a single rpc/db call instead of several small ones,
where the latencies then add up
Change-Id: Ice9ab0a9c1b783c059687e1d992eea1f97cb3193
=> ResourceTracker: Fetch Bdms up front

nova/virt/vmwareapi/special_spawning.py
Please see the commit-messages for details.
=> vmware: special_spawning add removing of rule and fix creation

nova/virt/vmwareapi/cluster_util.py, nova/virt/vmwareapi/vim_util.py, nova/virt/vmwareapi/vmops.py
The function is already implemented in oslo.vmware
Change-Id: I48ab65502d1cd825fede6f73e764a5926d949beb
=> Vmwareapi: Replace nova is_vim_instance with oslo.vmware one

nova/scheduler/filters/cpu_info_migration_filter.py, nova/tests/unit/scheduler/filters/test_cpu_info_migration_filters.py
Depends on #307 and will be much more local when merged.
Find via the hostmapping the right cell and get the compute-node from there
=> Fix cpu info migration filter

tox.ini
=> Rename py27 to py in tox

custom-requirements.txt, nova/cmd/shellinaboxproxy.py, nova/conf/shellinabox.py, nova/console/shellinaboxproxy.py
=> Shellinaboxproxy update

nova/bigvm/manager.py
rc_fields got removed with the placement-api removal from Nova and is replaced by its own package os_resource_classes.
SchedulerClient got resolved, because it was only proxying functions through to SchedulerReportClient at some point in time, so we use SchedulerReportClient directly now.
Change-Id: Iabeae6e01f9615be7c122d1e3fd719a1e53762d9
=> bigvm: Replace rc_fields and scheduler.client imports

nova/tests/unit/virt/vmwareapi/test_vmops.py, nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/vmops.py
=> Softer soft anti affinity

nova/tests/unit/virt/vmwareapi/test_vmops.py, nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
=> Support bfv rescue

nova/tests/unit/virt/vmwareapi/test_driver_api.py, nova/virt/vmwareapi/driver.py
Copy the relevant code from the libvirt driver.
=> vmware: Add resource overcommit ratio support

.pre-commit-config.yaml
We need to seperate the arguments for tox
from the ones to the linter
Change-Id: I6d7ee1d95f0ca17fa6c04a3546a7f907cc6393f1
=> Fix linting with tox4

.pre-commit-config.yaml
Change-Id: I3edf0d3c6deb8385adc1095c7e3c09526e2d4d65
=> Use pre-commit from openstack/nova master

nova/bigvm/manager.py
When asking for allocation candidates, nova-scheduler calls placement
with a parameter of "root_required" for required & forbidden traits
which ignores sharing providers connected via aggregates. Therefore
we need to switch creating BigVM RPs as proper children of the host
RPs again.
This works because nova-scheduler now supports nested resource
providers.
Reverts commit 5143fd8e27.
Change-Id: I6801fce6cf95c37096a045799d30cbde843c509a
=> Revert "bigvm: Create RPs without parent"

nova/policies/server_groups.py
Change-Id: Ibc78cbd80ae49df9be60f6d9eda56a47d9ffe39e
=> server-groups: Restrict update API to members/admins

nova/conf/vmware.py, nova/scheduler/client/report.py, nova/tests/unit/virt/vmwareapi/test_vmops.py, nova/virt/vmwareapi/constants.py, nova/virt/vmwareapi/driver.py, nova/virt/vmwareapi/vim_util.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
=> vmware: sync traits to custom attributes

nova/api/openstack/compute/routes.py, nova/api/openstack/compute/sap_admin_api.py, nova/policies/__init__.py, nova/policies/sap_admin_api.py, nova/tests/unit/test_policy.py
Change-Id: I29382c21701de04c974181618e27cab453a3395d
=> SAP Admin API - custom API endpoints

nova/conf/base.py, nova/tests/unit/test_utils.py, nova/tests/unit/virt/vmwareapi/fake.py, nova/tests/unit/virt/vmwareapi/test_driver_api.py, nova/tests/unit/virt/vmwareapi/test_vm_util.py, nova/utils.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
- vmware: Add CPU reservation support
- vmware: Update inventory with reservable CPU count
=> CPU Reservation

nova/api/openstack/compute/sap_admin_api.py, nova/conf/base.py, nova/policies/sap_admin_api.py, nova/tests/unit/test_policy.py
Change-Id: I88a9b36de44ddd967c1acb5d542f7c105d6a4e42
=> SAP: add get_scheduler_settings admin API

nova/api/validation/extra_specs/vmware.py, nova/tests/unit/virt/vmwareapi/fake.py, nova/tests/unit/virt/vmwareapi/test_configdrive.py, nova/tests/unit/virt/vmwareapi/test_driver_api.py, nova/tests/unit/virt/vmwareapi/test_vmops.py, nova/virt/vmwareapi/error_util.py, nova/virt/vmwareapi/vm_util.py, nova/virt/vmwareapi/vmops.py
Please see the individual commits' message.
=> Support per-vm EVC via Flavor extra_specs

nova/objects/instance.py
This method is not needed anymore, because the DB table `instance_type_extra_specs` is not used anymore, and is empty in all our DBs by now.
Change-Id: I87e686c0ce9124a74877a0783787820c36aecc35
=> vmware: Remove _recover_flavor_from_cell_instance_types()

nova/virt/vmwareapi/volumeops.py
=> fixup! Vmware: Live-Migration of VMs
