nova/api/openstack/common.py
nova/api/openstack/compute/legacy_v2/contrib/os_tenant_networks.py
nova/api/openstack/compute/legacy_v2/contrib/quota_classes.py
nova/api/openstack/compute/legacy_v2/contrib/quotas.py
nova/api/openstack/compute/legacy_v2/contrib/server_group_quotas.py
nova/api/openstack/compute/legacy_v2/contrib/used_limits.py
nova/api/openstack/compute/legacy_v2/limits.py
nova/api/openstack/compute/limits.py
nova/api/openstack/compute/quota_classes.py
nova/api/openstack/compute/quota_sets.py
nova/api/openstack/compute/tenant_networks.py
nova/api/openstack/compute/used_limits.py
nova/api/openstack/compute/views/limits.py
nova/cmd/api.py
nova/cmd/manage.py
nova/compute/api.py
nova/compute/manager.py
nova/compute/utils.py
nova/db/api.py
nova/db/sqlalchemy/api.py
nova/network/floating_ips.py
nova/objects/quotas.py
nova/quota.py
nova/scheduler/manager.py

This adds two new extra specs:
When an instance with such a flavor is started, it counts against the instance quota *for that flavor* instead of the overall instance quota. So a quota of
instances = 5
instances_baremetal6 = 2
means that there can be up to 2 instances with `flavor_name = 'baremetal6'`, and up to 5 instances with flavors without the `quota:separate` flag (so up to 7 instances total).
Instances of such a flavor do not count towards the RAM and CPU quotas (only, as the name says, towards the instance quota), such that these two resources reflect the virtualized capacity only. Previously called `quota:no_reserve_cpu_ram`.
* These two specs are separate because `quota:separate` may also be useful for virtualized flavors (e.g. to restrict the usage of large HANA flavors).
I …

baremetal quota handling

---

nova/db/sqlalchemy/migrate_repo/versions/320_fix_quota_double_spending.py

This fixes an issue where multiple usage records were created for the same project, user and resource. When those were updated during a reservation, quota would be spent multiple times for a single VM.

add a uniqueness constraint to the quota_usages table

---

nova/compute/api.py

When allow_resize_to_same_host is set to True, and
if more than one hypervisors are configured, nova
resize api fails to force the resize to the same

Resize: allow_resize_to_same_host=True fails (fd9508038351d027dcbf94282ba83caed5864a97 commit number)

---

nova/virt/vmwareapi/vm_util.py

… a3c410f7943676b09cedf7bb3fb2c135f8e6c6ed commit id

vmwareapi: Do not rely on naming convention for root_disk detection - a3c410f7943676b09cedf7bb3fb2c135f8e6c6ed commit id

---

nova/conf/compute.py

Adding missing cfg max_concurrent_builds_per_project - acb63d3f0512dad58eec7725ce26ef8b9546d544 commit from mitaka-m3 merge

Limit instance creation cfg fix - acb63d3f0512dad58eec7725ce26ef8b9546d544 id

---

nova/virt/vmwareapi/ds_util.py
nova/virt/vmwareapi/images.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

- Import image as VM template per datastore.
- First look on other datastores before fetching the image.
- Create instances by cloning the VM template.

VMware: Image as VM template

---

nova/virt/vmwareapi/cluster_util.py

Until now, affinity and soft-affinity meant the same thing from the
vcenter side, because the same rules were created in the vcenter by the
openstack vmware driver.
This commit now changes the meaning of soft-affinity: no rule will be
created in the vcenter for soft-affinity, thus making the affinity work
only on nova-compute basis and not on ESXi host basis.

Soft-affinity only means same cluster

---

nova/compute/api.py
nova/conductor/tasks/migrate.py
nova/conf/compute.py

This fix adds configuration flag for avoiding migrations across
clusters. Setting `always_resize_on_same_host` config option
will put the instance host in `force_hosts` resulting in
resize the instance on the same host.

Fix resize instance cross cluster issues

---

nova/conf/vmware.py
nova/virt/vmwareapi/vm_util.py

If we don't reserve all memory, there's a swap file pre-created for
every VM on the ephemeral storage - even if it's unused.
But this option comes at the price of not being able to over-commit
memory.
Related issue: CCM-9589

Add option to reserve all memory

---

nova/compute/manager.py
nova/conf/compute.py

Nova regularly checks the power state of every VM on the hypervisor. The
default behaviour for VMs not matching the requested power state is to
call the stop API. But since vmware hypervisors are actually a cluster
of hypervisors that do HA on their own. In the process of doing HA
failover, especially if that failover fails for some time e.g. because
of a still held lock, VMs are reported as SHUTDOWN by the API. If we
call the stop API then, nova will shut down the VM once it's RUNNING
again, because the stop API sets the expected/user-wanted VM state to
SHUTDOWN. This would effectively disable the VMware HA.
Therefore, we're introducing a new setting
`sync_power_state_unexpected_call_stop` which can be used to disable the
call to the stop API.

Make stop on unexpected power state configurable

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vmops.py

fetch_cluster_properties
The function name is changed, since the function is fetching
cluster properties and does no validation, which creates confusion.

Rename validate_vm_group function in cluster_util.py to

---

nova/compute/resource_tracker.py
nova/conf/vmware.py
nova/tests/unit/compute/test_resource_tracker.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/host.py
nova/virt/vmwareapi/vm_util.py

This can be used to have different CPU/memory reservations for hosts
depending on the hostgroup they're in. We can also set defaults in
percent with this instead of only static values as supported by
CONF.reserved_host_memory_mb and CONF.reserved_host_cpus.
NOTE: Setting these settings too differently per hostgroup for the same
cluster might result in placement API getting confused and scheduling
being impossible, as the `max_unit` is still set to the maximum per
cluster. In case of our HANA HVs placement would therefore always
consider the HANA HVs max unit. That should be no problem as smaller VMs
should always fit.

[vmware] Add configurable reservations per hostgroup

---

nova/api/openstack/compute/console_output.py
nova/tests/unit/api/openstack/compute/test_console_output.py

As the comment states, it's only relevant for XML and should be removed
in the future. The future is now, as we want fully colored logs :D

[api] Don't remove ANSI from console output

---

nova/tests/unit/scheduler/filters/test_bigvm_filters.py
nova/utils.py

Instead of checking for the flavor attribute `quota:separate` we now use
the same flavor attribute as the scheduler: `capabilities:cpu_arch`.
This is done for consistency reasons and to make sure we can also use
separate quota for the big VMs if we want to.

is_big_vm() detects baremetal like nova-scheduler

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vmops.py

It's possible to create a boot-from-volume instance with
instance.image_ref set to something - even something different than the
actually booted volume's image according to
https://bugs.launchpad.net/nova/+bug/1648501. Therefore, we cannot rely
on an empty image_ref for BFV detection and instead use
nova.compute.utils.is_volume_backed_instance now. This prohibits the
vmware driver from creating a disk on ephemeral store in addition to
using the volume and booting from the volume.

[vmware] Don't rely on empty image_ref for BFV detection

---

nova/compute/api.py
nova/tests/unit/compute/test_compute.py
nova/tests/unit/compute/test_compute_api.py

instead of returning exception on duplicate found with pagination enabled,
we fetch the full amount of instances from cells regardless of open
buildrequests and slice the result at the end to the requested length.
The nanny can clean the orphaned build-requests at any time while maintaining sane API results.

fix for pagination with duplicate instances

---

nova/scheduler/filters/bigvm_filter.py
nova/tests/unit/scheduler/filters/test_bigvm_filters.py

We want to define flavors, that can be used both for a full and a half
hypervisor, so customers don't have to juggle too many flavors.

[scheduler] Support multiple extra_specs values in big VM filter

---

nova/scheduler/filters/shard_filter.py
nova/tests/unit/scheduler/filters/test_shard_filter.py

We need those shards to scale further in an availability-zone. We shard
on project level by adding the appropriate tags to the project in
keystone.
This filter should only allow a host to pass if it's in an aggregate
having the requesting project's shard assigned.

[scheduler] Add a filter for vcenter shards

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

When attaching the volumes after a migration, we must guarantee
the order of the boot devices, otherwise the instance may not
boot due to boot disk not being attached first.
Therefore, we attach first the volumes that have specified
a boot_index by the order of that boot_index. The volumes with
default (-1) or without boot_index will be attached afterwards
as they came from the manager.

[vmware] attach the block devices by the boot_index order

---

nova/conf/scheduler.py
nova/scheduler/filters/bigvm_filter.py
nova/tests/unit/scheduler/filters/test_bigvm_filters.py

Before, the filter for placing big VMs supported a fixed configuration
dict of hypervisor cache to big VM memory size ratios, identified by
string keys. This became cumbersome if the list of ratios got longer.
Repurpose the 'host_fraction' extra spec parameter for big VMs to
support a float number (or comma-separated list of numbers) between 0
and 1 expressing one or more possible ratios of VM/hypervisor memory.

bigvm: Replace str-keyed host_fractions with ratio

---

nova/virt/vmwareapi/driver.py

Instead of just allowing to access a VM in state ACTIVE, it also makes
sense to access a VM currently running a rescue image and a VM running
after being resized.
Change-Id: If9f7a84ed06b438072378aa67ac0dd3b33b0c01e

[vmware] Allow get_mks_console in RESCUED and RESCUED state

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

In the case when a relocate fails, we must ensure the detached volumes
aren't hanging, so we must make sure they get reattached after an
exception is thrown.

[vmware] handle relocate failure and rollback the detached volumes

---

nova/conf/scheduler.py
nova/scheduler/weights/resize_same_host.py
nova/tests/unit/scheduler/weights/test_weights_resize_same_host.py

When an instance is resized, it is rescheduled. So far the scheduler considers all hosts equally when scheduling an instance, the current host of the instance is not special.
It is arguably desirable to keep instances on the same host if possible and keep instance migrations between hosts to a minimum.
This change addresses this by introducing a prefer-resize-to-same-host weigher, which weighs the host the instance is currently running on higher than all others. This only comes into play if the filters have included the current host in their output. Notably this change does not in any way "add" the resources used by the instance to the available host resources, in short, the current host would need enough space for "another", resized, instance to be eligible.
Fixes CCM-13235

[scheduler] Add prefer-resize-to-same-host weigher 

---

nova/compute/manager.py
nova/network/neutronv2/api.py
nova/tests/unit/compute/test_compute.py
nova/tests/unit/network/test_neutronv2.py

If the instance info_cache is corrupted somehow, like during
a host reboot and the ports aren't wired up properly or
a mistaken policy change in neutron results in nova resetting
the info_cache to an empty list, the _heal_instance_info_cache
is meant to fix it (once the current state of the ports for
the instance in neutron is corrected). However, the task is
currently only refreshing the cache *based* on the current contents
of the cache, which defeats the purpose of neutron being the source
of truth for the ports attached to the instance.
This change makes the _heal_instance_info_cache periodic task
pass a "force_refresh" kwarg, which defaults to False for backward
compatibility with other methods that refresh the cache after
operations like attach/detach interface, and if True will …

Force refresh instance info_cache during heal

---

nova/api/openstack/compute/servers.py

If we don't have any node supporting a specific baremetal flavor, we
don't have a quota resource for it, which makes requests trying to
create a server with that flavor die in a bad way (HTTP 500):
Unexpected exception in API method: InvalidQuotaMethodUsage: Wrong quota method check used on resource instances_zh1emx1.large
Which looks like this to the user:
$ os server create --flavor zh0hpe1.large --key bla --image 0c5135e7-eb1a-49bb-9945-2d82a72353c6 test-joker-bare-1 --network cc-demo_private
Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
<class 'nova.exception.InvalidQuotaMethodUsage'> (HTTP 500) (Request-ID: req-020b17cd-206d-4763-951b-4ace5f335321)
We now catch the exception and provide a better error-message:
$ …

[api] Better error message for invalid baremetal flavor

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vmops.py

Add function to clean empty VM groups and call it with the groups a VM
was in as a filter after unregistering the VM. Unregistering the VM
removes the VM from the group, but only if we re-retrieve the groups
from the vCenter. Before cleaning, we take the same lock that's used for
updating/creating VM groups, so we don't delete a group we're just
trying to add to again with a parallel task.
Co-Authored-By: Martin Midolesov <mmidolesov@vmware.com>
Change-Id: I12d71204b1afd741974cecae73f2e46df1e6d949

[vmware] Fix VM group deletion

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Mark the BigVM host as used after resizing a VM, same as after
spawning a new VM.
Applied for both big -> big resizes as well as small -> big resizes.

[bigvm] Set host as used after resize

---

nova/cmd/manage.py
nova/objects/instance_mapping.py
nova/objects/request_spec.py

Add `nova-manage api_db purge_request_specs` command to clean up db for the upcoming mariadb migration.

[manage] Purge old request specs for deleted instances

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/driver.py

When deleting an instance didn't go through and nova retries on the next
nova-compute restart, an instance not existing in the back end anymore
can lead to an uncatched exception in the vmware driver prohibiting
instance deletion. This is the case, if the instance had volumes
attached, because `_detach_instance_volumes()` always powers off the
instance - which cannot work if the instance doesn't exist anymore.
While the code already catched `ManagedObjectNotFoundException`, it also
needs to catch `InstanceNotFound` raised by `vm_util.get_vm_ref()` to
complete the deletion as seen in the traceback below (which comes from a
queens codebase):
Traceback (most recent call last):
File "/nova/compute/manager.py", line 874, in _init_instance
self._delete_instance(context, instance, bdms)
File …

vmware: Handle exception in destroy with attached volumes

---

nova/compute/manager.py

Using `vm_state` instead of `vm_states` is a bug which leads to:
AttributeError
'unicode' object has no attribute 'ACTIVE'

fixup! Sync states when in SUSPENDED state

---

nova/conductor/manager.py
nova/conductor/tasks/live_migrate.py
nova/scheduler/filters/shard_filter.py
nova/tests/unit/conductor/test_conductor.py
nova/tests/unit/scheduler/filters/test_shard_filter.py

Projects having multiple shards in the same AZ can lead to the scheduler deciding to use a host in another shard/vCenter. We currently cannot support this and any migration started will fail.
We can repair the instance with `hammer vc gen-wrong-bb-fix-cmds` when accommodating the command for shards, but that's manual effort. The instance will stay powered off until someone looks at it.
To fix this, the conductor passes the instance's host as a scheduler-hint, so we can adapt the `ShardFilter` to filter out hosts of other shards.
In the long run, we want to support such migrations, too.

Prohibit migration between vCenters for multi-shard projects

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/host.py

If we disabled the host automatically, because we couldn't reach the
vCenter, we set a flag on the `VCState`. This flag is lost with a
compute-node restart, but the service stays disabled.
We now check the service's state and compare the disabled_reason on
startup to detect if we disabled the service automatically. This means,
the driver will automatically enable the service again if it can reach
the vCenter.
Change-Id: I1e49d5962adfd0bb585543c7a5580d343628f687

vmware: Detect automatically disabled host on restart

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Upsize and downsize to/from a BigVM flavor was accidentally switched,
and the test didn't catch it because it forced the result of
is_big_vm().
Correct the resize direction and improve the tests by un-mocking
is_big_vm() and setting actual BigVM memory sizes on the instance
flavors in the tests.

bigvm: Fix small<->big resize direction detection

---

nova/objects/resource_provider.py
nova/tests/functional/db/test_resource_provider.py
test-requirements.txt

When a resource-provider gets overused in placement, e.g. because a host
in the cluster it represents goes down or because one memory dimm of
multiple fails, we need to be able to (offline) migrate/resize a VM to
reduce the pressure on the host and to make the resize process more
stable.
For that, we check in the call setting the allocations if for every
allocation with a value for a resource, there's also an allocation
removing such a resource - namely switching the allocations from one
consumer to another as is done for migrations.

placement: Allow switching resources on overused providers

---

nova/objects/console_auth_token.py
nova/tests/unit/objects/test_console_auth_token.py

For noVNC 1.1.0 or newer, there must be a 'path' query parameter only,
instead of 'token'.
This patch allows 'path' query parameter being present in the
novncproxy_base_url configuration. In that case, we just append
the token to it.

console_auth_token: allow pre-existing 'path' query parameter for novnc

---

nova/objects/instance.py

Cast Decimal to Int in _get_counts, similar to _get_counts_in_db.
SQLalchemy func.sum() returns Decimal on MySQL. When the usage limits
are calculated unless explicitly converted to Int we end up with
Decimal objects that cannot be JSONified and thus causing
ValueError: Circular reference detected.

Fix project limits calculation.

---

nova/consoleauth/manager.py

Starting with Rocky, the validate_console_port is expecting the port
to be a string, so nova-consoleauth has to fulfill that expectation.
This commit should be carried up to Train, before nova-consoleauth
code gets completely removed.
The regression was introduced here: https://github.com/openstack/nova/commit/ba269da87a7ac0130f87fca78083a09231533c2

nova-consoleauth: port is expected to be string by validation

---

nova/compute/manager.py
nova/console/shellinaboxproxy.py
nova/objects/console_auth_token.py

Rocky introduces database tokens and deprecates the nova-consoleauth
service. Thus, shellinabox needs to access the tokens from the
database as well.
This still supports the old nova-consoleauth by enabling it via
the [workarounds]/enable_consoleauth.

shellinabox: add support for db tokens

---

nova/conf/vmware.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vm_util.py
test-requirements.txt
tox.ini

This is necessary with multi-version clusters where migrating e.g. on
resize needs to be possible.
Change-Id: Idc287c4dfa2b5d6a6a837a5014063417c8e13768

vmware: Add option for setting default hw_version

---

nova/virt/vmwareapi/special_spawning.py
nova/virt/vmwareapi/vmops.py

Two little syntax issues with the current rocky code.
There are 60+ unit tests failing for me as well...

Fix python3 syntax in rocky

---

nova/compute/rpcapi.py

Starting with rocky, we will have the "long_rpc_timeout" option
available, which is also used in this call. rocky also add some handling
for longer RPC calls, which - afaics - make the caller see a broken call
faster than the long RPC timeout. Since we're planning to upgrade to
rocky in the very near future, we can get along with not monitoring the
calls for now, but increasing the timeout by hardcoding the future
default-value.
This should lead to nova-api not running into MessagingTimeout that
often and thus delete the block_device_mapping entries properly, as it
can find out via Cinder, that the volume is already attached or
attaching.
Change-Id: I4d6b137d2f5659265adb54da1094a63e30b7b3e4

Increase timeout for reserve_block_device_name RPC call

---

nova/conf/base.py
nova/utils.py
nova/virt/vmwareapi/special_spawning.py
nova/virt/vmwareapi/vmops.py

We don't want them to move anymore. This might hinder our efforts to
spawn big VMs, but the nanny is supposed to help us here.
Change-Id: I5ebdbe2f287d50c9b9a755166702c3eccea62b14

vmware: Set large VMs as partiallyAutomated in DRS

---

nova/scheduler/filters/shard_filter.py
nova/tests/unit/scheduler/filters/test_shard_filter.py

If the project tags from keystone contain the tag "sharding_enabled"
then the hosts in _all_ shards will pass the shard filter for this
project.
This was done to facilitate both enabling sharding (only one simple
tag to set), and mainly for frontend code to detect sharding status
(mostly) without parsing tag strings. (If sharding is not enabled,
then vc-* tags will have to be parsed to find out which shard(s) the
project is on.)

Handle sharding-enabled in scheduler shard filter

---

tox.ini

As upstream also states, this script may fail for forks, like ours,
so instead of disabling it via environment variables in CI only,
we remove it completely from tox.ini so that pep8 commands will
work out of the box for everyone.

remove check-cherry-picks.sh invocation for pep8

---

nova/conf/vmware.py
nova/virt/vmwareapi/vm_util.py

We want to be able to configure new VMs with our currently-disabled vSPC
services, because it doesn't seem to be possible to reconfigure a serial
port on a running VM - other than setting it to connected and
startConnected. Therefore, we add a config option.
Change-Id: I0b9d7a7d1445c2017756146068e287628a39bec6

vmware: Optionally attach disconnected serial ports

---

nova/bigvm/manager.py

We need to call _ensure_resource_classes instead.
Change-Id: I2329db43adc00e04b07d16d312361ae5e669d298

bigvm: SchedulerReportClient._ensure_resource_class got renamed

---

nova/tests/unit/virt/vmwareapi/test_vim_util.py
nova/virt/vmwareapi/vim_util.py

If the `obj_list` parameter to the `vim_utils.get_properties_for_a_collection_of_objects()` function is empty, an empty list was returned. The non-error path returns a `vim.RetrieveResult` object, with an iterable "objects" attribute.
Introduce a dummy class `EmptyRetrieveResult` which behaves like `vim.RetrieveResult` for the empty case, and return an instance if the list of objects to be queried is empty.

Fix empty result for vim_util.get_properties_for_a_collection_of_objects()

---

nova/cmd/manage.py
nova/tests/unit/test_nova_manage.py

"nova-manage placement sync_aggregates" doesn't support Ironic hosts,
because they have multiple compute nodes. In general, Nova doesn't
support aggregates for Ironic hosts. But we still use them for assigning
an availability zone to a rack (a building block) of nodes grouped into
a Nova host.
Therefore, we patch above-mentioned command to handle a list of (in most
cases one) compute node UUIDs, only erroring out if the host we find
multiple compute nodes for doesn't look like an Ironic host (based on
having "ironic" in the name).
Change-Id: I4f7e5fd82c51ce5d6f42089beb5a70e469ec54df

manage: Support Ironic in sync_aggregates

---

nova/db/sqlalchemy/migrate_repo/versions/391_placeholder.py
nova/db/sqlalchemy/migrate_repo/versions/392_fix_internal_access_path_max_length.py
nova/db/sqlalchemy/models.py
nova/tests/unit/db/test_migrations.py

The 'internal_access_path' column of 'console_auth_tokens' table has the
type String with max length of 255 characters which might not be enough
when used with VmWare and that will cause a DBDataError.
This migration changes the internal_access_path type to be Text with max
length of 65535 characters.
Closes-Bug: #1900371

Add migration for 'internal_access_path' column to allow more than 255 chars.

---

nova/conf/flavors.py
nova/objects/flavor.py
nova/tests/functional/api_sample_tests/test_flavors.py

When the extra_spec _"catalog:alias"_ is present list an additional alias flavor in the flavor list, with a name of the extra_spec value.
For the alias the `flavorid` is appended with _'\_alias_id'_ in order to have a unique id, with a straightforward removal process, without any further DB lookups.
This is done to enable phasing out flavors. "Aliased" flavors appear when listing available flavors, but they don't actually exist and get automatically converted into their actual flavor counterparts on flavor show and when creating servers.
This means inspecting a flavor by name and deploying a server with a flavor by name will result in the actual flavor being shown or used for creation, respectively.

Alias flavor names from catalog:alias extra_spec

---

nova/conf/vmware.py
nova/virt/vmwareapi/vm_util.py

After the instance is deleted in VSphere its syslogs are deleted along with it, which hinders post-mortem debugging.
Add a config flag `forward_instance_logs_to_loginsight` to forward all instance logs to VMware's Loginsight monitoring service, to be able to inspect them after the instance is gone.

vmware: Add Mirror-instance-logs-to-syslog config

---

nova/conf/flavors.py
nova/objects/flavor.py
nova/tests/functional/api_sample_tests/test_flavors.py

During renaming/restructuring of flavors, multiple old flavors get mapped to a single new flavor. But `catalog:alias` on the new flavor previously only accepted a single alias pointing to the deprecated flavor.
The interpretation of `catalog:aliases` extra_spec is changed so that the value can be a single alias name or a comma-separated list of multiple names.
Compare: a6e4b321 - "Alias flavor names from catalog:alias extra_spec"

Allow multiple flavor aliases for single flavor

---

nova/bigvm/manager.py
nova/conf/base.py
nova/conf/vmware.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/utils.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

See sapcc/nova#159 for previous discussion. This version targets rocky, and fixes a small but significant bug. (See below.)
---
[memreserv] Reserve memory for certain flavors
VMs with reserved memory have better memory allocation performance and less softlock issues. Coincidentally, many larger VMs also have high performance requirements that puts strict demands on the quick availability of their memory.
Implement memory reservation and a configurable maximum number of cluster hosts that could theoretically fail and still let all VMs with memory reservation boot up.
Nova provides the flavor extra_spec "quota:memory_reservation" which reserves the given amount of memory. This change does not make use of that feature, but instead introduces a parallel custom resource …

LargeVM memory reservation 2

---

nova/bigvm/manager.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

- Split BigVM memory overuse trigger log messages
- Fix reserved-memory-usage RP lookup key name in BigVM manager
- Only use flavor-reserved-memory when not reserving all memory (via config or for BigVM)
- Prohibit reserving more memory than the flavor has specified

Memory reservation fixes

---

nova/scheduler/filters/bigvm_filter.py
nova/tests/unit/scheduler/filters/test_bigvm_filters.py

If one of the new `CUSTOM_NUMASIZE_*` host traits is required on a (BigVM) flavor, then the host was already matched in placement, and the filter can succeed early.
This is a temporary measure until we phase out host-fraction filtering altogether when the old BigVM flavors are disabled.

bigvm/hostsizefilter: Pass filter if NUMA trait required

---

nova/virt/vmwareapi/constants.py
nova/virt/vmwareapi/special_spawning.py

We need to handle vCLS VMs created by DRS, as they don't move automatically.

big VMs on vSphere 7

---

nova/virt/vmwareapi/special_spawning.py

Not all VMs have a "config.managedBy" attribute ...
Change-Id: I0fc0b4d0c8027dd6b2c45060597cbadb60f0d649

vmware: Fix special spawning vCLS detection

---

nova/bigvm/manager.py

Total memory being zero should generally not happen, hence emit a warning.
But _reservable_ memory could go to zero in practice, hence emit only an info log line.

BigVM: Fix div-by-zero for memory-usage-percents

---

nova/bigvm/manager.py

In-buildup clusters show up without complete resource inventory, i.e.
without memory resources. Log and skip these resource providers.
Also add debug-logging when skipping due to missing reservable memory
resource. This was the only "continue" in the else section without
logging. This complicated finding out why exactly resource providers
are skipped.

bigvm: Skip getting RPs without MEMORY_MB resources

---

nova/objects/instance.py

Probably with switching to mariadb, the query got too slow in bigger
regions, because mariadb joins the instance_extra and the instances
table, which have more than 100.000 rows in a bigger region. Since we
only need one instance_extra entry per missing flavor, we force mariadb
to use a temporary table to join against instance_extra, which is much
faster it only contains as many rows as we're missing flavors.
Attention: This code probably doesn't run on PostgresSQL anymore,
because "GROUP BY" doesn't behave the same way there.
Change-Id: If0e95cd1d62c00490dc86ca6273e07f8d2fd98ac

Optimize quota:separate query

---

nova/scheduler/filters/shard_filter.py
nova/tests/unit/scheduler/filters/test_shard_filter.py
nova/utils.py

We don't expect ironic nodes to be in a vc-* host aggregate,
therefore we log it to debug instead of error for such nodes.

shard_filter: debug log for ironic nodes without VC aggregate

---

nova/api/openstack/placement/lib.py
nova/api/openstack/placement/objects/resource_provider.py
nova/api/openstack/placement/schemas/allocation_candidate.py
nova/api/openstack/placement/util.py
nova/tests/functional/api/openstack/placement/db/test_allocation_candidates.py
nova/tests/unit/scheduler/test_utils.py

Porting https://github.com/sapcc/placement/pull/1 into rocky.
This commit makes it possible to pass a list of consumer UUIDs to ignore
when retrieven allocation candidates. This can be useful for
implementations replacing a VM on resize instead of copying it. Some
care has to be taken on the client side to not overbook the
resource-provider, but there's another check when trying to allocate the
resources that should make sure of that.

Ignore passed consumers in allocation candidates

---

nova/compute/api.py
nova/tests/unit/api/openstack/compute/test_serversV21.py

This reverts commit 79693220128d7a5ceb2b76b5d3c3ce765d4dbd9f.
After some discussion, we want to enable big VMs for
affinity/anti-affinity again. This is a requirement by one customer, who
wants to run a Hana with a replica and make sure they're not on the same
host. While we never spawn big VMs on the same host, we might move them
around. Whatever tooling we use for that needs to take the DRS rules
into account then.
Not using soft-(anti-)affinity might lead to VMs being unspawnable, if
the free host happens to be in the wrong cluster.

Revert "[api] Prohibit certain VMs from joining server groups"

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

When a VM is storage-vMotioned, the name of the folder its files are in
can change. Then, a rescue command trying to put the rescue disk into a
folder named after the instance's UUID cannot work anymore and actually
raises a FileNotFoundException for the directory path.
To fix this, we now take the root VMDK's folder and copy the rescue
image into that.
Change-Id: Icef785b96e51942e7bac2df10c116078c77fedc4
Closes-Bug: #1915815

Cherry-Pick: vmware: Handle folder renames in rescue cmd

---

nova/virt/vmwareapi/vmops.py

We're currently unable to remove a DRS override as our SOAP library is
unable to create an appropriate request accepted by the vCenter.
Therefore, we still allow the resize to work for now and have to
manually remove the override later on.
We keep the code in, so we get a reminder in the logs and sentry, that
this needs fixing. We just don't fail the resize for it.
Change-Id: I4d344347860c7d97d6f4b2e68d9bbac069d71b74

vmware: Do not reraise exception on DRS override removal

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/host.py
nova/virt/vmwareapi/vmops.py

Follow the same pattern as in the other functions
Set the local variable client_factory to the client factory
of the current session and use that in the function

VmWare: DRY getting the client factory

---

nova/virt/vmwareapi/vmops.py

The logic is inverted: Only if use_property_collector is active, we actually expect
the cache to contain sensible values for the vm-state. So, only then it makes
sense to log a cache miss

VmWare: Logging cache miss with PropertyCollector enabled

---

nova/virt/vmwareapi/images.py

The image-meta-data passed to a live-migration doesn't have the attribute set
Accessing it inconditionally will cause an exception

Image owner atribute may not be set

---

nova/tests/unit/virt/vmwareapi/fake.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py

By setting the vcenter version to MIN_VC_VERSION (<NEXT_MIN_VC_VERSION),
the tests trigger logging the deprecation warning.
By setting it to NEXT_MIN_VC_VERSION, we can avoid that

VmWare: Fix deprecation warning in unit tests

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vif.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py
nova/virt/vmwareapi/volumeops.py

The code was getting the hardware devices in multiple places directly,
and then (often, but not always) normalising the array.
Functions getting the device array then also had to normalise the array again.
By consolidating the retrieval and the normalisation in a function,
the code becomes less repetitive

VmWare: Don't repeat yourself with hardware devices

---

nova/conductor/tasks/live_migrate.py
nova/conf/workarounds.py

Vsphere can migrate just fine from newer to older vcenters,
but the live-migration pre-check tests for that.
It is more a work-around to make an option for that,
as a proper solution would delegate that to the driver.

Vmware: Make live-migration hv-version check optional

---

nova/virt/vmwareapi/vm_util.py

For cross-vcenter migrations (live or not), we need to create
ServiceLocatorSpec. This change provides the required functions

VmWare: Create ServiceLocatorSpec

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_ds_util.py
nova/tests/unit/virt/vmwareapi/test_ds_util_datastore_selection.py
nova/virt/vmwareapi/ds_util.py
nova/virt/vmwareapi/special_spawning.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

In various places, own version of iterating over the results are implemented,
sometimes even faulty.
The following functions where only getting up to vmware.maximum_objects objects (100 by default)
vm_util.get_all_cluster_mors, vm_util.get_stats_from_cluster,
_SpecialVmSpawningServer._get_vms_on_host, _SpecialVmSpawningServer.free_host
Only in _SpecialVmSpawningServer._get_vms_on_host we might get over the 100 items,
and actually have missed ones.
Previously, the results were fetched in batches of up to vmware.maximum_objects items.
Using WithRetrieval yields an iterator to the results, which pages transparently to
the next request.
Receiver of the output of the results where changed to consume an iterator, where easily
possible.

Vmware: Use WithRetrieval to get all results

---

nova/tests/unit/virt/libvirt/test_driver.py
nova/tests/unit/virt/test_block_device.py
nova/virt/block_device.py

Prior to this change, when the user passes a block-device-mapping to the server create api call,
the compatibility logic would fail to detect, that we do have a cinder 3.44+ api, and create legacy volume attachments.
Boot from Volume is apparently a major concern for driving the change, as the commit messages are referring to it,
but the change is affecting *all* cinder volume related attachments on server creation.
Essentially this is the change de5bce6ea, with all predating changing concerning block-devices, removing the volume-type change not part of rocky.
The code prior to this change 
- would check, if a newly created volume has an attachment-id, which it hasn't
- and since it hasn't a attachment-id, attach it with the legacy-code
The new code relies on 3.44 api (or later) and …

Server Creation with Block Device Mapping with Cinder 3.44+ Volume Attachments

---

nova/virt/vmwareapi/vm_util.py

This extracts getting the hosts and reservations from a cluster in
get_stats_from_cluster into its own function get_hosts_and_reservations_for_cluster.
For cross-vcenter vmotion, we need to specify hosts, and we want
the same ones as we use elsewhere.

Vmwareapi: Split out getting hosts from get_stats_from_cluster

---

nova/tests/unit/virt/vmwareapi/test_configdrive.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

Previously vmops was calling the private function
`vm_util._get_server_groups` and that function would access to nova.object.
All other code seem to work more the way, that the nova.object retrieval is
responsibility of a VmOps (or VolumeOps) instance. `vm_util` only works
with vmware-objects (plus passed instances).
Additionally, `update_cluster_placement` was called in
`VMwareVMOps.build_virtual_machine`, which is also called for creating
a virtual machine for a vm-template out of an image.
In that case, the server-groups of the instance requiring the image
would be wrongly applied to the vm-template of the image.

Vmware: Refactor server groups

---

.pre-commit-config.yaml

pre-commit uses a newer flake8 version, which causes new
warnings, which are partly in conflict with the old version
So we disable them instead.
Change-Id: I8a854268d3c7ea8d885915105917041430871010

Use tox to run flake8

---

nova/api/openstack/compute/server_groups.py

When retrieving multiple - or all - server groups, the code tries to
find not deleted members for each server group in every cell
individually. This is highly inefficient, which is especially noticable
when the number of server groups rises.
We change this to query all members of all server-groups we will reply
with (i.e. from the already limited list) in advance and pass this set
of existing uuids into the function formatting the server group. This is
more efficient, because we only do one large query instead of up to 1000
times the number of cells.
Change-Id: I3459ce7a8bec9a9e6f3a3b496a3e441078b86af0

api: Pre-query not deleted members in server groups

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/special_spawning.py

The interface for creating rules/groups in `cluster_util` was very limiting as it was only written with the local function for applying server-groups on vm-creation.
With us trying to implement a sync-loop for server-groups, we need a little more freedom. There are explicit functions for creating vm/host groups and vm rules and their appropriate specs for applying those rules/groups to a `ClusterConfigSpecEx` now, and the old interface is available modul-local for compatibility, reusing the new functions.

VMware: cluster_util group and rule creation refactoring

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

In the upcoming sync-loop for DRS rules, we need to map all instance UUIDs mentioned in a server-group to a moref. The idea is, to use the cache for this. Therefore and to reduce the number of queries to the vCenter, we pre-fill the cache.

VMware: warmup moref cache

---

nova/virt/vmwareapi/vm_util.py

There is actually a generic method for converting arrays
returned from the API, make use of it.
It follows more closely upstream.

VMWare: get_array_items instead of own

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/host.py

No need for an additional indirection, as the driver is the only
user of the information, and query the value directly
Change-Id: I6d44910c420de4c76b6112904ccfebe3ec923098

Vmware: Query Drs state directly in driver

---

nova/virt/vmwareapi/driver.py

When init_host() is called, we keep the provided host as an attribute so
we can later refer to it when e.g. getting all instances for the host
the driver is running for.
Change-Id: I261006a727125a87c204564f95ec8797060cd557

vmware: Save the ComputeNode host name for later

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_volumeops.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/volumeops.py

We used to do 2 reconfigure calls for a vmdk attach, which could lead to
inconsistencies if the second - the extraConfig update - did not
succeed. For the VMware driver, the volume looked not attached to the
server then and thus wouldn't get detached later on.
We know change this procedure to attach the vmdk and add the extraConfig
entry at the same time, thus making both fail or none of them - same for
the detach case.
Since we only need this for vmdks, attach_disk_to_vm() and
detach_disk_from_vm() only do it if the right parameters were supplied.
The underlying functions then only update a given config_spec instead of
creating a new one and reconfiguring the cluster.
Besides producing less inconsistencies, this should also make the
volume-attachment/-detachment process minimally faster, …

vmware: Make volume attach and extraConfig update atomic

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/constants.py
nova/virt/vmwareapi/vmops.py

We want to create a sync-loop for applying/removing server-groups
changed by the user via API. For this we need to be able to distinguish
between driver-created DRS groups/rules and admin-created ones. To do
this, we introduce a prefix for the DRS group/rule name, which will work
as an identifier later on.
Since we're now using not only a UUID, but a UUID with a prefix, we
change GroupInfo to have a "name" attribute instead of a "uuid"
attribute.
As we're changing how DRS groups/rules look, we need a migration to run
before deploying this to production.
Change-Id: I07ecd1953a85d0f53082fa9b0c49b80c2c9bf9d3
---
We have a migration script ready in the toolbox repository.

vmware: Use a prefix in DRS groups and rules

---

.pre-commit-config.yaml

Rocky is not fully python3 compatible
i.e. use of the keyword async
Using python2 in the pre-commit hook fixes
the check tripping over incompatible syntax for python3
Change-Id: I98515842a24fd348934378a842c76ea291ed0006

Use python2 for pre-commit-hook in rocky

---

nova/api/openstack/compute/routes.py
nova/api/openstack/compute/schemas/server_groups.py
nova/api/openstack/compute/server_groups.py
nova/compute/utils.py
nova/objects/fields.py
nova/objects/instance_group.py
nova/policies/server_groups.py
nova/rpc.py
nova/tests/unit/api/openstack/compute/test_server_groups.py
nova/tests/unit/notifications/objects/test_notification.py
nova/tests/unit/objects/test_objects.py
nova/tests/unit/test_policy.py

Customers want to be able to update the members of a server-group not only during spawning of an instance, e.g. to spawn a second instance for a service because of new requirements, while the first instance was not spawned in a server-group.
This is a pure api/DB change and does not reflect on any underlying system like the VMware hypervisor.

api: update server group members

---

nova/virt/vmwareapi/cluster_util.py

The attribute group/rule gets removed by the underlying SOAP library if
it's empty. Therefore, we have to check for it to exist instead of
trying to iterate over it unconditionally.
Change-Id: I443338bf97dcf83478e0a9971179480ecb01c009

vmware: Fix getting rules/groups in cluster_util

---

nova/virt/vmwareapi/vmops.py

If a VM moves across clusters, the DRS override for
the cluster will be gone. So we need to set it again
Change-Id: Ic5d010de95f194ea660f10805c46ad43762bd83e

Vmware: Disable DRS after migration

---

nova/network/neutronv2/api.py
nova/network/security_group/neutron_driver.py

This commit removes tenant (project) filter for security group list in two places `nova-api` and `nova-compute`. Nova will not be able to get the wrong security groups (that are not allowed) because in these places user's context is used.
By adding additional debug logs I printed the list of security groups that Nova got from Neutron API and compare it with the available security group list. Both lists match 100%.
Debug logging:
```
nova-compute-bb90-c648d8b9c-5n9lg nova-compute 2021-09-20 14:02:01,324.324 6 DEBUG nova.network.neutronv2.api [-] SECURITY GROUPS: [u'06d74a24-d305-423b-a0cc-f4c6ea69e6f1', u'1a5b0497-010e-469d-8b3a-7aa9e19df07b', u'2c56e6ad-ec2a-4380-b414-4eae771e9e8c', u'2c8a1686-4ebb-4b66-9582-8cb1c2206f1b', u'2ffa46b2-d21b-4373-9b20-37907b74d8ef', …
```

Remove tenant filter for Security group search in  VM creation to be able to use shared Security Groups.

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

After the recent changes of syncing server-groups,
the syncing of rules in cluster_util.update_placement has become unused.
The code can be simplified as a preparation for live-migration,
as it will add complexity.
VMops.update_cluster_placement now calls
- sync_instance_server_group, which fetches _the_ server-group
for the instance and syncs it with the existing VMOps.sync_server_group
- update_admin_vm_group_membership handles the membership to special_spawning_vm_group
Since that is the only remaining use-case of cluster_util.update_placement,
the function has been renamed to update_vm_group_membership and reduced to
that use-case
Change-Id: I94c311790610fc4658f9b06ac052ad46660f1cea

Vmware: Refactor update_cluster_placement

---

nova/db/sqlalchemy/api.py
nova/virt/vmwareapi/vmops.py

During a migration, we have to consider the following situations:
- On the source-host, we have to remove the group constraints
as soon as the migration has started, in order to avoid that
the constraints disallow the movement
- On the destination-host, we have to add the rules as soon
as the vm is in the vcenter, before the instance.host has been
updated. Otherwise, we might remove rules added by the migration
itself.
The parameters to specify the cluster and the host are in
preparation for the migration-task, which needs to call
the sync for the source-host on the destination-host
Change-Id: I2b3c626ecf4a33c3baa20489b66bb7e6b69459b6

Vmware: Sync server-group during migration

---

nova/virt/vmwareapi/vmops.py

If a vm has none of the requested properties,
propSet will not be set. So, we need to skip over that instance
Change-Id: Ia633fecb021bffe1557820e36c33ef53cf90db83

Vmware: Handle missing propSet in list_vms

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vmops.py

In order to migrate a vm (within a vcenter) we need
to be able to remove a vm from a vm-group constraining
it to a set of hosts
Change-Id: I8ef5ebdc54b3c3de0310e461132828aa251ee657

Vmware: Add option to remove vm from vm-group

---

nova/virt/vmwareapi/images.py

When migrating or resizing an instance, the driver looks
for vsphere locations properties stored with the image
We can't do that though, if the image has been deleted,
so we fall back gracefully
Change-Id: I55c4d1f49e3c6fc0bb89794ac1b44da99ce009ca

Vmware: Handle deleted image graceful

---

nova/conductor/tasks/live_migrate.py
nova/objects/migrate_data.py
nova/tests/unit/notifications/objects/test_notification.py
nova/tests/unit/objects/test_objects.py

Split out the changes for live-migration which are affecting the conductor
Basing it on the upstream VMWareLiveMigrateData 1.0 version in the hope
that we have an easier path merging the code with upstream eventually
Change-Id: I5d8417c836d735122e033eeb72f7671b2558afc4

Vmwareapi: Live-migration changes on conductor level.

---

nova/virt/vmwareapi/vmops.py

When retrieving the instances being part of a server-group, we retrieved
all instances - even deleted ones. Those ended up not being in the moref
cache and were thus searched in the vCenter - one by one in a very slow
manner, as they didn't exist anymore. This also meant, that spawning a
server in a server-group with lots of deleted members took a very long
time.
We now only query non-deleted members of a server-group and thus should
not run into the same bottleneck in syncing server-groups anymore.
Change-Id: I35cc52449782d4d76b54259a2e28460c01ac7ad6

vmware: Ignore deleted instances in server-group-sync

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vm_util.py

The function is not used (except in tests),
so we might as well remove it
Change-Id: Ic9e31a35867f362562374507b946cfeb9b508b75

Vmwareapi: Remove unused _get_folder

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vm_util.py

With switching to vm_util.get_hardware_devices(), we automatically use
vim_util.get_array_items(), which already takes care of accessing the
VirtualDevice attribute automatically. Thus, we get a list instead of an
object and cannot access a VirtualDevice attribute anymore.
The fix is to just iterate over the list of objects.
Change-Id: I3e031d3954c6361d96d26c13e47ae161056b0b78

vmware: Fix AttributeError in find_rescue_device()

---

nova/network/model.py

When using python-raven to send exceptions to Sentry, the serialization
might run into a deadlock if the exception happens during server build
and the NetworkInfoWrapper object is not done.
We mitigate this by registering our own serializer in raven, which does
not go into the content, but just prints the greenthread.
Change-Id: Ie170e951e4d8d007a48d5878ec957e2e95155628

Add a NetworkInfoAsyncWrapper serializer to raven

---

nova/network/model.py

We unintentionally registered the NetworkInfoAsyncWrapper instead of the
NetworkInfoAsyncWrapperSerializer which could not work and broke sentry
reporting.
Change-Id: Ib6f436ded2481d99dc1b32c54974c37b94281b81

Fix NetworkInfoAsyncWrapper serializer registration

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/special_spawning.py

There's too much manual effort involved in spawning big VMs, because of
partiallyAutomated large VMs. We do not move them, but just manually
mark compute node as free. Therefore, we want Nova to do the same now.

vmware: Ignore partiallyAutomated VMs left on a host

---

nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vmops.py

When at least one of the disks attached to the VM during snapshotting is
associated with a profile containing storage IO control, the clone
operation done during snapshotting fails with `VmConfigFault` and the
more detailed "IO Filters are configured for the Source Disk
vm-174314:2002, but no storage-policy selected for the destination.
Select an appropriate storage-policy for destination disk.".
We can mitigate this by specifying the profile in the RelocateSpec part
of the CloneSpec, i.e. add an VirtualMachineRelocateSpecDiskLocator for
each disk to be detached into the "location.disk" attribute. Setting
the "profile" attribute on the VirtualDeviceConfigSpec we create for
specifying the removal does not help.
This will not add a profile for volumes attached before Cinder's queens …

vmware: Specify volume profiles while snapshotting

---

nova/tests/fixtures.py

The notification causes a load of all projects
for each flavor created, times for each test set up.
Patching it out reduces total runtime of the unit
tests by 20%
Change-Id: Ib3b1f2bc401be67d043b723ecff59a0c45d9f81d

No Flavor notification in Test Fixture setup

---

nova/api/openstack/compute/server_groups.py
nova/tests/unit/api/openstack/compute/test_server_groups.py

When we add/remove a server to/from a server-group, we have to update
the server's RequestSpec's instance_group attribute, because this is
used during scheduling when resizing a server to record a list of
appropriate hosts for the instance.
AttributeError: 'NoneType' object has no attribute 'hosts'
File "oslo_messaging/rpc/server.py", line 166, in _process_incoming
res = self.dispatcher.dispatch(message)
File "oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
return self._do_dispatch(endpoint, method, ctxt, args)
File "oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
result = func(ctxt, **new_args)
File "oslo_messaging/rpc/server.py", line 229, in inner
return func(*args, **kwargs)
File "nova/conductor/manager.py", line 94, in wrapper
return fn(self, context, *args, …

api: Update RequestSpec when updating server-group membership

---

nova/quota.py

We're using a single function to compute the usage of multiple quota
reources. There's already a check in place that prohibits recomputing
that data, if the resource's name is already in the data. When computing
usage data, we use the instances belonging to a user/project. If that
user/project does not have any baremetal instances of a flavor, we don't
add the flavor's resource to the usage data. This means, the check is
unable to skip recomputing the data.
If "instances" is already in the usage data, our shared function must
have been called already. Therefore, if we encounter a resource having a
name starting with "instances_" - which should be only true for
resources we created for baremetal flavors - we can skip the
recomputation even if the resource's name is not in the usage data.

Skip recomputing baremetal quota usage

---

nova/objects/instance.py

Mariadb still doesn't do the best job in executing that query (takes
~3s currently). The subquery alone takes roughly 0.3s and if we use the
result of that query (in my tests 5 UUIDs) in a new query's WHERE, it
takes only 0.06s. This should make up for the additional round-trip to
the DB.
Change-Id: I73aa89b0b76a0620265fb20caf4a18eb1f5f8311

Optimize quota:separate query again

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/driver.py

Since the VM is gone after a migration,
it won't be possible to update the vm-group membership
Change-Id: I04c62f400a522bf9fe5828199c0dff80a1004f42

Vmware: No update_admin_vm_group_membership in post_live_migration

---

nova/virt/vmwareapi/driver.py

We have to catch all exceptions in the post-migration
steps, otherwise a roll-back will be initiated which
we cannot do properly as the VM has already been migrated
with the vsphere api.
Instead the VM will be set in error state as it will require
a manual inspection and intervention by an operator.
Change-Id: I75faecfdd48c9f40d243aecdd2b90b89e5158335

Vmware: Catch Exception in post-migration

---

nova/virt/vmwareapi/vm_util.py

The attribute 'details' isn't always set,
so we have to raise the exception without
recovering the missing vm_ref
Change-Id: Ib1fbd90e03a0f36fb5833c71ae6cdde454e74958

Vmwareapi: Handle missing details in ManagedObjectNotFoundException

---

nova/compute/manager.py
nova/network/model.py
nova/tests/unit/compute/test_compute_mgr.py

This change modifies _get_neutron_events_for_live_migration
to filter the event to just the subset that will be sent
at plug-time.
Currently neuton has a bug where by the dhcp agent
send a network-vif-plugged event during live migration after
we update the port profile with "migrating-to:"
this cause a network-vif-plugged event to be sent for
configuration where vif_plugging in nova/os-vif is a noop.
when that is corrected the current logic in nova cause the migration
to time out as its waiting for an event that will never arrive.
This change filters the set of events we wait for to just the plug
time events.
Related-Bug: #1815989
Closes-Bug: #1901707
Change-Id: Id2d8d72d30075200d2b07b847c4e5568599b0d3b

Cherry-Pick: only wait for plugtime events in pre-live-migration

---

nova/tests/unit/virt/vmwareapi/stubs.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_network_util.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/tests/unit/virt/vmwareapi/test_volumeops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/session.py

The object is not only used by the driver,
but in practically all modules of vmwareapi.
It reduces a bit the scope of the driver module
itself
Change-Id: I76e446945c312e5b4fea54d04335d7d20ef3829d

VMware: Split out VMwareAPISession

---

nova/compute/manager.py
nova/conf/cinder.py
nova/exception.py
nova/tests/fixtures.py
nova/tests/unit/compute/test_compute.py
nova/tests/unit/compute/test_compute_mgr.py
nova/tests/unit/virt/test_block_device.py
nova/tests/unit/volume/test_cinder.py
nova/virt/block_device.py
nova/volume/cinder.py

Until now, we handled shard-migration transparently in Cinder. This did
not work well, if the migration took longer than Cinder's RPC-timeout -
which is a given for volumes over a certain size.
To address this, Nova will now initialize the migration and wait for it
to finish. To help with that, Cinder gained a new endpoint to migrate
volumes by connector - because we pass the vCenter UUID inside the
connection_capabilities of it - and by returning a new error-message on
attachment_update, so Nova knows that the update failed because the
volume is in another shard  - or rather assigned to another backend.
Since we now have to migrate a volume, callers of attachment_update now
have to provide a volume_id in addition to the previous parameters.
Change-Id: …

Let Nova migrate volumes between shards

---

nova/tests/unit/virt/test_block_device.py
nova/tests/unit/volume/test_cinder.py
nova/virt/block_device.py
nova/volume/cinder.py

From the instance we can derive the shard and pass the value
as a scheduling hint to cinder
Change-Id: I81faa098634916b64af147d20427796036dd2cbb

[SAP] Shard as volume creation scheduling-hint

---

nova/volume/cinder.py

Please see the 2 commit-messages for details.

Set gobal_request_id and reduce time between volume status checks in migrate-by-connector

---

nova/tests/unit/virt/vmwareapi/fake.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/host.py
nova/virt/vmwareapi/vm_util.py

Joined the collection of the cpu-info with the host-stats in order to
avoid calling twice the property collector in different places to
get information over all the host.
Split the code into getting the data and aggregating it over the cluster.
Partly to split the logic into more easily consumable parts,
but it is also a preparation for exposing the individual esxi-hosts
as hypervisors.
Change-Id: I383854bb0e956519e3bdc42121b59d43ca54743d

VmWare: Refactored resource and inventory collection

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vm_util.py

Clients such as the cli expect cpu_info to be a json dict,
so returning a string is breaking them.
By aggregating the individual attributes, we also work around
having different cpu models with the same flags in a cluster
not yielding any information. Now we can see that the model
mismatch, but the cpu feature flags are matching.
Change-Id: Id552121b642ec90f6e06be09825ab7339531f9d6

Vmware: Aggregate cpu_info on item level

---

nova/virt/vmwareapi/vm_util.py

Host in certain states (such as disconnected ones) do not report
quickStats about memory usage, so we have to assume values
here, which is better than failing updating the stats for all hosts.
Since they are not available, both the usage as well as the free
memory will not be added to the total for the cluster.

Vmware: Handle empty quickStats in host stats

---

nova/tests/unit/virt/vmwareapi/fake.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vim_util.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py

The code was previously using the object-id to
lookup an object, meaning that you couldn't pass
a newly created Managed-object-reference like you
could over the vmware-api.
Now the lookup happens over the ref-id string,
and in turn some functions were refactored
to take that into account.
Change-Id: I70b87ed5f4fe08076745f9bc389b0f42930395cf

VMwareapi: Use refs as index for fakedb

---

nova/compute/manager.py
nova/virt/driver.py
nova/virt/libvirt/driver.py

The attachment operation may potentially be long-running,
so a batch of attachments/reservations may be causing a rpc timeout.
The compute node still blocks on the lock and creates a bdm regardless.
This replaces the instance lock with a bdm specific lock on
bdm allocation.
That means reserving a device name can run concurrently with
detaching a volume.
This will likely create a different behaviour, but since the
value has a non-zero probability of being wrong anyway,
we risk it being wrong more often.

Do not block on reservation

---

nova/virt/vmwareapi/vmops.py

Instead of only reserving memory for big VMs, we now also reserve memory
for large VMs, because we want to help DRS with scheduling those VMs
correctly (i.e. by configured memory) and improve performance for the
VMs.
Change-Id: I8b3a1a63ea4c1d459ed5c731d5ef94343d9e6046

vmware: Reserve memory for large VMs

---

nova/virt/vmwareapi/images.py

Since .ova files contain more than just the .vmdk, the size reported by
glance is not the size of the actual upload. Since olso.vmware now has a
guard against not-finished uploads integrated, we cannot just use the
size from glance. Instead, we switch to using the size of the .vmdk as
reported by the tar file.
Change-Id: I05cdc3fc47974ceb34a72704d79b3f7c54c05d41

vmware: Use vmdk size from .ova files

---

nova/network/model.py

As it turns out, the serializer for NetworkInfoAsyncWrapper we
introduced in Ie170e951e4d8d007a48d5878ec957e2e95155628 and which's
registration we already fixed in
Ib6f436ded2481d99dc1b32c54974c37b94281b81 was never called, because the
more generic IteratorSerializer is registered before it via the base.py
of raven.utils.serializer. Since SerializationManager.register() always
appends to the list, there's no way for us to let our serializer come
earlier in the list than getting dirty. While we could monkeypatch our
own implementation of a SerializationManager into the module, too, we
rather just access private parts of the already existing
SerializationManager and prepend our serializer to the list of
serializers, as it's more specific than the others.
Change-Id: …

Fix NetworkInfoAsyncWrapper registration order

---

nova/compute/manager.py
nova/tests/unit/compute/test_compute_mgr.py
nova/utils.py

The nova.utils.spawn and spawn_n methods transport
the context (and profiling information) to the
newly created threads. But the same isn't done
when submitting work to thread-pools in the
ComputeManager.
The code doing that is extracted to a new
function and called to submit the work to the
thread-pools.
Change-Id: I9085deaa8cf0b167d87db68e4afc4a463c00569c

Transport context to all threads

---

nova/volume/cinder.py

Try migrate_by_connector on attachment_create
As we cannot conform to the original design of
volumes being accessible to all hosts, we raise an
exception, in the case that is not possible and
migrate the volume to a cinder-host, where it is possible.
That is already done for attachment_update, which is called
for the normal attachment of a volume to a server.
In case of a live-migration (step pre_live_migration)
creates a new attachment for the target hypervisor node,
and passes the connection_info with it.
It can fail for the same reason, as in attachment_update.
As before, we need to migrate the volume to a cinder-host
where the volume is accessible to the target hypervisor.
Change-Id: I6232f34f47ae2bcb78d83f587d8edaf701c2341b

Try migrate_by_connector on attachment_create

---

nova/compute/api.py
nova/conductor/manager.py
nova/conductor/tasks/live_migrate.py
nova/objects/request_spec.py
nova/scheduler/filters/cpu_info_migration_filter.py
nova/scheduler/utils.py
nova/tests/unit/compute/test_compute_api.py
nova/tests/unit/scheduler/filters/test_cpu_info_migration_filters.py

The confusing names led apparently to a parameter passed through
scheduler_hint, which is containing a filter_property,
which has scheduler_hints, which is where the parameter should
have ended up.
Additionally, set the live-migrate flag instead of inferring
the state from other flags.
The flags are persisted, so we need to overwrite them.
Change-Id: Id80bfd2f3e4771856cc0d85bc1b85a7d14f3b136

Pass _nova_check_type through scheduler_hints & set live_migrate

---

nova/image/glance.py
nova/tests/unit/image/test_glance.py
releasenotes/notes/bug-retry-corrupted-download-5798b0df44a00e4e.yaml

Adding IOError in list of catching exceptions in order to
fix behavior when nova-compute wouldn't retry image download
when got "Corrupt image download" error from glanceclient
and had num_retries config option set.
Closes-Bug: #1950657
Change-Id: Iae4fd0579f71d3ba6793dbdb037275352d7e57b0

Cherry-Pick: Retry image download if it's corrupted

---

nova/tests/unit/virt/vmwareapi/test_images.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/images.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py
nova/virt/vmwareapi/volumeops.py

We changed the code to ignore the file-name,
as a vmotion will result in renaming of the files
breaking the heuristic to detect the root disk.
Instead we were taking the first disk,
when the uuid parameter was set.
The uuid parameter is not set when working with shadow-vms
and vms for image import. So, no special handling is
needed, we always want the first disk in those cases too
and so we can scrap the uuid argument.
Change-Id: Ib3088cfce4f7a0b24f05d45e7830b011c4a39f42

Vmware: Remove uuid parameter from get_vmdk_info call

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

Based on the stable managed object reference "infrastructure" from #288 (and changes to the tests #290),
instead of retrying the whole code block with a decorator, wrap the moref in a proxy-object, and search for the new moref in case we get a ManagedObjectNotFoundException.
Similar to the stable volume managed-object references #289,

Stable VM References

---

nova/virt/vmwareapi/vmops.py

The clone created in a snapshot would also contain
the nvp.vm-uuid field in the extra-config.
If we delete then the original vm, the fallback mechanism
of searching for the VM by extra-config would trigger,
and find the snapshot and delete that instead.
Change-Id: I6a66fa07dfe864ad4deedc1cafe537959cd969f4

Vmware: Remove nvp.vm-uuid on clone

---

nova/tests/unit/virt/vmwareapi/fake.py
nova/virt/vmwareapi/vm_util.py

The equality test is only used by the tests
so it is better implemented there.
Change-Id: I51ee54265c4cc2b4f40c0b83f785a49f8a8ebce4

Vmwareapi: Move equality test to tests

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_volumeops.py
nova/virt/vmwareapi/volumeops.py

Based on top of #288.
We wrap the "volume_ref" in a proxy-object, which will search of a shadow-vm with the stored id in case of a ManagedObjectNotFoundException. That way, we can detach volumes also when a shadow-vm has been un- and re-registered.

Stable Volume References

---

nova/conf/vmware.py
nova/objects/migrate_data.py
nova/tests/unit/notifications/objects/test_notification.py
nova/tests/unit/objects/test_objects.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/ds_util.py
nova/virt/vmwareapi/error_util.py
nova/virt/vmwareapi/vmops.py

This set of patches enables us to make sure that the first two servers in a server-group are placed on different datastores, levering a naming-scheme for datastores to achieve this.
For this to work properly, all volumes attached to a VM need a profile assinged to the VM for that disk. Otherwise, the storage-vMotion will just fail no matter if there's a profile in the VirtualMachineRelocateSpec or not. We will have to remedy that in production and need to patch the attachment process in Nova to include the profile-id for volumes.

VMware: root disk anti affinity

---

nova/scheduler/filters/shard_filter.py
nova/tests/unit/scheduler/filters/test_shard_filter.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/error_util.py
nova/virt/vmwareapi/rpc.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

Prior to this, the driver was performing migration/resize in a
way that could lead a VM into an inconsistent state and wast not
following the way nova does the allocations during a migration.
Nova expects the driver to do the following steps
* mirate_disk_and_power_off() - copies the disk to the dest compute
* finish_resize() - powers up the VM in the dest compute
This change removes the RelocateVM_Task and introduces a new
CloneVM_Task instead, in migrate_disk_and_power_off().
Change-Id: I9d6f715faecc6782f93a3cd7f83f85f5ece02e60

[vmware] refactor resize/migration to follow nova principles

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_volumeops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/volumeops.py

If we attach a volume to a VM, we have to set the storage-profile.
Otherwise, the VM will not be compliant to the profile and - especially
on VMFS datastores - cannot be storage-vMotioned around if the
storage-profile includes storage-IO control. With setting the profile
for each disk-attachment, the VM also shows compliant to these profiles
in the UI.
Change-Id: Idad6293dc7dfdf46fed584b9c116c03f928d44fe

vmware: Set profile on volume attachment

---

nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vmops.py

This removes redundant code introduced in
Idad6293dc7dfdf46fed584b9c116c03f928d44fe
Also fixes warnings of `tox -e pep8`.

vmware: Remove redundant code of profile_id.

---

nova/virt/vmwareapi/session.py

If a shadow-vm is missing, we raise an AttributeError,
which is not clearly identifying the reason of the failure.
We better re-raise the original ManagedObjectNotFound exception,
so it is more clearly identifiable
Change-Id: I954c57e97961833208743bc88e3ce75ad23cfe8c

VMwareapi: Raise proper exception for missing shadow-vms

---

nova/virt/vmwareapi/vm_util.py

If multiple nics are attached, they need different device-keys
otherwise the vmwareapi will reject the request
Change-Id: I0aa58ad11c499e9423c7ecc7998325b05dd9147e

Vmwareapi: Fix attachment of multiple nics

---

nova/virt/vmwareapi/vm_util.py

When spawning a VM with more than 128 cores, we set numCoresPerSocket
and some flags e.g. vvtdEnabled. We missed to add the same flags when
resizing to a VM having more than 128 cores. This patch remedies that.
Change-Id: I381a413ecf80af14dd4bf1dfde2d070976b6477a

vmware: Set appropriate settings for resize to > 128 cores

---

nova/virt/vmwareapi/vmops.py

When simply cloning the original VM, the size might not
fit on the target hypervisor.
Resizing it to the target size might not fit on the
source hypervisor.
So we simply scale it to minimal size, as we are going
to reconfigure it to the proper size on the target
hypervisor anyway.
Change-Id: Ia05e5b3a5d6913bfcef01fa97465a1aaa69872d0

Vmwareapi: Migrate disk with minimal vm

---

nova/virt/vmwareapi/vmops.py

An error needs manual intervention, and an exception debugging from
a developer. This, however, is a known behaviour which potentially
can lead to problems, hence a warning
Change-Id: I9479fb6405485e763a6344e7f44a60f75891adcb

Vmware: Warn about failed drs override removal

---

nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

When VMs with lots of CPUs are running for a longer period of time, a
task to reconfigure the VM might end up hanging in the vCenter.
According to VMware support, this problem happens if those VMs are
running for a longer period of time and with the large number of CPUs
have accumulated enough differences between those CPUs, that getting
them all into a state where a reconfigure can be executed takes more
time than the default 2s (iirc). The advanced setting to increase this
time is "migration.dataTimeout".
For simplicity reasons and because it shouldn't hurt (according to
VMware), we set it on all big VMs. That way, we do not have to figure
out if the VM consumes enough CPUs of the hypervisor to need this
setting.
Change-Id: Id8bda847c9e48997b385d9e1079ee9e99af9b8e8

vmware: Set migration.dataTimeout for big VMs

---

nova/conf/scheduler.py
nova/scheduler/weights/resize_same_shard.py
nova/tests/unit/scheduler/weights/test_weights_resize_same_shard.py

This filter enable to select same host-aggregate/shard/VC for instance
resize because it could take more time to migrate the volumes over other
shards.

Add PreferSameShardOnResizeWeigher.

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

In #324 there was introduced a minimal configuration for the
cloned VM. However, _clone_vm was never called with that config.

Fix #324 Migrate disk with minimal VM

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

Resizing to a different flavour may imply also
a different hw-version, so we need to set it
otherwise it will stay on the previous one,
which may be incompatible with the desired configuration.
Only upgrade is possible though.
Change-Id: I7976a377c3e8944483a10fdada391e8c51640e30

Vmwareapi: Set hw version on resize

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

Be more strict in the upgrade policy,
and only upgrade on resize, if the flavor demands it.
Not if the default has changed
Change-Id: I25a6eb352316f986b179204199b098a418991860

Vmware: Only change hw_version by flavor

---

nova/bigvm/manager.py

These changes make it so that we can use placement to filter for AZs instead of the AvailabiltyZoneFilter.
We previously didn't use aggregates in placement and thus `nova-bigvm` didn't properly handle those or even removed them.

bigvm: Handle AZ aggregates properly

---

nova/compute/api.py
nova/tests/unit/compute/test_compute.py
nova/tests/unit/compute/test_host_api.py
nova/tests/unit/virt/xenapi/test_xenapi.py

Use node name to sync the nova aggregate to placement resource provider
aggregate.
Change-Id: I08f2f07c0c695d1dd5b4fa72d0155e02b1872b0a
closes-bug: #1877229

Cherry-Pick: Fix aggregate placement sync issue

---

nova/virt/vmwareapi/cluster_util.py

The DRS rules can be read from the "rule" attribute, not from the
"rules" attribute. We found this, because Nova wasn't deleting
DRS rules for no-longer-existing server-groups.
Change-Id: I86f7ca85d9b0edc1406a54a6f392bfff8f0af00d

vmware: fix get_rules_by_prefix() wrong attribute

---

nova/virt/vmwareapi/vmops.py

When syncing a server-group's DRS rule(s) we now also enable a found
rule in case it is disabled. We don't know how this happens, but
sometimes rules get disabled and we need them to be enabled to guarantee
the customer the appropriate (anti-)affinity settings.
Change-Id: Ibc8eb6800640855513716412266fcbb9fbc4db42

vmware: Enable disabled DRS rules in sync

---

nova/virt/vmwareapi/vmops.py

When we don't find any datastores for whatever reason, we don't have the
"dc_info" variable set and thus cannot call
self._age_cached_image_templates() with it as it results in an
UnboundLocal exception.
Change-Id: I2dca6d2d6ab7ca5cbc4ef7d2c316faaf6edfee7d

vmware: Fix UnboundLocal error in manage_image_cache

---

nova/virt/vmwareapi/vm_util.py

The properties may not be set, if the host is disconnected.
Change-Id: I1c53477e891b5b95859ca267fcad8cd1bff260ef

VMWareapi: Handle missing Host properties

---

nova/conf/vmware.py
nova/tests/unit/virt/vmwareapi/test_images.py
nova/virt/vmwareapi/images.py

By using HttpNfcLeasePullFromUrls_Task we can convert an import
lease to pull the image from a Swift URL, instead of nova pushing
the bytes into the HttpNfcLease.

[vmware] Pull the image from Swift directly

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/rpc.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

These changes implement the following for live-migrating vms with config-drive cdroms:
- First detach the config-drive forcefully (it is hopefully not read during that time)
- Copy the iso over to the destination datastore
- Migrate the VM as before
- Reattach the cdrom on the VM
On failure, the cdrom is re-attached again
This depends on sapcc/oslo.vmware#23

Live-Migrate With Config-Drive CD-Rom

---

nova/bigvm/manager.py

This reverts commit a8c511287c2f696082767c86e04cbca81df00078.
This has the side-effect of providing the CUSTOM_BIGVM resource to all
resource providers in the same shard and AZ. We don't want that not only
because this means any BB could just spawn a big VM, but also because
nova-compute then does not find its bigvm resource provider and can't
set it to reserved and thus it will never be marked as used for
nova-bigvm.

Revert "bigvm: Mirror aggregates to bigvm provider"

---

nova/tests/unit/volume/test_cinder.py
nova/volume/cinder.py

Since the mission is to delete the attachment, Cinder returning a 404 on
attachment deletion call can be ignored. We've seen this happening where
Cinder took some time to delete the attachment so Nova retried as it got
a 500 back. On this retry, Nova got a 404 and left the BDM entry as
leftover while aborting the deletion, that already happened by driver.
Change-Id: I15dd7b59a2b3c528ecad3b337b92885b4d7bd68f

volume: Treat 404 on attachment_delete as OK

---

nova/virt/vmwareapi/vmops.py

Since we don't explicitly set a disk as boot disk and instead rely on
the order the disks have on the VirtualMachine, we need to make sure we
attach the root disk first.
Change-Id: I3ae6b5f053a3b171ed0a80215fc4204a2bf32481

vmware: Attach root disk first

---

nova/conf/base.py
nova/utils.py
nova/virt/vmwareapi/vmops.py

We've recently changed that not all large VMs need DRS disabled - only
the ones over 512 GiB memory. The VMs in the previously also included
range for large VMs of 230 GiB - 512 GiB do still need memory
reservations, though. While we could do this via flavor, we failed to do
so. Additionally, this would limit the amount of large VMs we can spawn
on a cluster.
To keep the same behavior we previously had for large VMs, we now split
memory reservations from big/large VM detection with the following
result:
1) a big VM will get DRS disabled - big VMs are VMs bigger than 1024 GiB
2) a large VM will get DRS disabled - large VMs are VMs bigger than 512
GiB
3) all VMs defining CUSTOM_MEMORY_RESERVABLE_MB resources in their
flavor get that amount of memory reserved
4) all VMs above …

Support split of large VMs and memory reservation handling

---

nova/virt/vmwareapi/ds_util.py

Apparently, the vmware api can report datastores with more free space
than capacity, which causes an exception in the olso_vmware api
So we limit the free space to the capacity

[vmwareapi] Limit free space of datastore to capacity

---

custom-requirements.txt
nova/db/api/legacy_migrations/versions/061_rocky.py
nova/db/main/legacy_migrations/versions/390_rocky.py
nova/db/main/migrations/versions/8f2f1571d55b_initial_version.py
nova/tests/unit/compute/test_compute_mgr.py
nova/tests/unit/virt/test_block_device.py
test-requirements.txt
tox.ini

We cannot use the upper-contraints.txt with URLs anymorme, because newer
pip doesn't like that. Additionally, we want our repositories with full
git history around for easier debugging - the other services are doing
it like that, too.
Change-Id: Ia5d8fe096e15b9b244573d662ea73613b3c68744

Add oslo.vmware stable/xena-m3 as custom requirement

---

nova/conf/cinder.py
nova/volume/cinder.py

When Nova computes the wait time for volume-migration, it uses the
volume size. For really small volumes (e.g. 1 GiB) the computed time is
lower than the overhead added by the API and RPC calls inside Cinder.
Therefore, Nova times out to wait for the migration, even though the
migration happens as expected.
To fix this, we now set a minimum migration timeout that defaults to 10min.
Change-Id: I1532054524653bc9dfaf5010f3250ea6bff03701

cinder: Define minimum migration timeout

---

nova/context.py
nova/tests/unit/test_context.py

If a RequestContext has already been created in the current
threadlocal, we should copy the request_id and global_request_id
from it when creating a new one.
Currently, creating a new context with context.get_admin_context()
will end up generating new request IDs for it.

copy request IDs from the current context

---

nova/scheduler/weights/resize_same_host.py
nova/tests/unit/scheduler/weights/test_weights_resize_same_host.py

We can make use of the changes to the scheduler to simplify the internal logic.
If it is a resize is now stored in the request_spec, as well as the source host, so we do not have
to reconstruct it from instance data anymore.
Change-Id: I4b016448a5a905a5d9833aa821daed186d7f1f8a

[scheduler] Refactored PreferSameHostOnResizeWeigher

---

nova/scheduler/filters/__init__.py
nova/scheduler/filters/affinity_filter.py
nova/scheduler/host_manager.py
nova/scheduler/weights/__init__.py
nova/scheduler/weights/affinity.py
nova/tests/unit/scheduler/test_host_filters.py
nova/tests/unit/scheduler/test_host_manager.py

Only in a subset of the situations the filters or weighers
are interested in the placement of very specific instances
for the scheduling decision.
But the host-manager fetches/holds all the instances for all
the hosts, which at a sufficient scale occupies the scheduler
fully with book-keeping of the instances.
As a first step, return the instance-ids each filter/weigher
is interested in, and skip on updating that information,
if none is required.
At a later step, the update can be limited to those instances.
Change-Id: I3ea05f98e300bbf0e4b0b42ad334e86d34b21ab6

[scheduler] Only fetch instances when weighers/filters request any

---

nova/scheduler/host_manager.py

The function is called from other code-paths as well, and we need to preserve the old semantics for use-cases besides the FilteringScheduler (such as the CachingScheduler)
Change-Id: Id99e08fa5e833b197324ccf525a5fbcdfcce318a

[scheduler] _get_host_states instance_uuids may be None

---

nova/scheduler/filters/affinity_filter.py

The refactoring was incomplete, still having the old function names instead of host_info_requiring_instance_ids
Change-Id: Ibb69e15654ec6818a1bc920b1c8197f6a3c52080

[scheduler] Fix host_info_requiring_instance_ids in AffinityFilter

---

nova/virt/vmwareapi/ds_util.py

Apparently, the vmware api can report datastores with more free space than capacity, which causes an exception in the olso_vmware api. Therefore, we limit the free space to the capacity.
Change-Id: If6013022a8a32029d43f9074eaaeea5b55855104

[vmwareapi] Limit free space of datastore to capacity 2

---

nova/cmd/shellinaboxproxy.py
nova/console/shellinaboxproxy.py

The old script was
- running check_output and therefore
- not printing the mitmproxy logs
- capturing the output in RAM
- only querying the first cell for tokens
- validating the request after having received a response from the backend, i.e. after having forwarded the unauthenticated request
- and probably having some strange interaction between eventlet and mitmproxy mixing up the validation with the requests (i.e. requests would be send through without validation despite the code clearly stating they should)
Change-Id: I2d1cd9a3f440705a8c8a075c8df62e5627facd90

SAP: Rewrite ShellInaBoxProxy as MiTM script

---

nova/virt/vmwareapi/special_spawning.py

Instead of immediately checking the default DRS behavior setting, we now try to find a free host first and only error out if we would need to rely on DRS to free up a host. This makes it possible to support BBs where an operator already freed up a host manually.
Change-Id: I22dbdcc9f135bbfc9ef05e13c801e88a78e64236

special_spawning: Check DRS behavior later

---

nova/virt/vmwareapi/vm_util.py

This is a fixup for commit 072b15f54b4 [vmware] Add configurable reservations per hostgroup
Change-Id: I191aedb0e3bba7698825771089cf134f320368ec

vmareapi: Fix jsonutils.load() needing bytes in Python3

---

nova/virt/vmwareapi/driver.py

With upgrading to Xena and thus Nova using newer microversions to talk to Placement, we cannot report floating point numbers for the resources anymore. This came up in DISK_GB, which is computed from MB and thus not always a round number.
We fix this by converting the numbers to int and thus cutting off the values after the comma. With that, we under-report resources, which seems better than over-reporting them, because we could not fit everything in when over-reporting.
Change-Id: I0d364f347afa235ed2b7e8ae90f5851275b7738e

vmware: Report DISK_GB as integers

---

nova/scheduler/filters/__init__.py
nova/scheduler/filters/affinity_filter.py
nova/scheduler/host_manager.py
nova/scheduler/weights/__init__.py
nova/scheduler/weights/affinity.py
nova/tests/unit/scheduler/test_host_filters.py
nova/tests/unit/scheduler/test_host_manager.py

Only in a subset of the situations the filters or weighers
are interested in the placement of very specific instances
for the scheduling decision.
But the host-manager fetches/holds all the instances for all
the hosts, which at a sufficient scale occupies the scheduler
fully with book-keeping of the instances.
As a first step, return the instance-ids each filter/weigher
is interested in, and skip on updating that information,
if none is required.
At a later step, the update can be limited to those instances.
Change-Id: I3ea05f98e300bbf0e4b0b42ad334e86d34b21ab6

[scheduler] Recent Patches for Xena (selective instance fetch, uuids None, unified host_info/passes/weigh)

---

nova/objects/service.py

We want to know when a service was first activated and last deactivated. For this, we log a line every time a service is enabled/disabled. The log line can then be saved in long-term storage and looked up again.
Change-Id: Ia904ac8108dd384d1675eba5250a38b77a5a8184

Log disabled/forced_down changes on services

---

nova/objects/service.py

We want to know when a service was first activated and last deactivated. For this, we log a line every time a service is enabled/disabled. The log line can then be saved in long-term storage and looked up again.
Change-Id: Ia904ac8108dd384d1675eba5250a38b77a5a8184

Log disabled/forced_down changes on services - xena

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vmops.py

Since VMware doesn't support the "mandatory" setting on VM-VM DRS rules, all rules we create are mandatory. This leads to VMs being unable to spawn in a cluster, if there are already as many VMs in the same soft-anti-affinity server-group as there are hosts in the cluster. Customers expect soft-anti-affinity to work also in this case.
To accommodate for that, we now split members of soft-anti-affinity server-groups into multiple chunks. Each chunk has the size of available hosts in the cluster. For each chunk, we create an anti-affinity DRS rule.
We try to make the members of each chunk stable by sorting the members in the server-group, but this commit probably still leads to more updates of DRS rules in those bigger server-groups.
Since there can be rules in a no-longer-used chunk and …

vmware: soft-anti-affinity can use multiple DRS rules - xena

---

nova/conf/base.py
nova/tests/unit/test_utils.py
nova/utils.py

Option `password_all_group_samples` allows us to sample `password_all_group_samples` times from the symbol groups, ensuring that we have from each symbol group `password_all_group_samples` occurrences in the password. 
Option `password_additional_symbols` allows us to add a fourth symbol group to make the passwords compliant with password policies, which require them.
See individual commits for details.

Add more password generation options

---

nova/cmd/mksproxy.py
nova/conf/mks.py
nova/console/mksproxy.py
nova/console/securityproxy/mks.py
nova/console/websocketproxy.py

Original code can be found at: https://opendev.org/x/nova-mksproxy
Integrate the code into nova as a builtin command.
Subclass `NovaProxyRequestHandler` for the `WebSocketProxy` by overriding just the handshake part. This made it necessary to refactor the handshake & connection code out of `new_websocket_client()` into a new `handshake_and_connect()` method in `NovaProxyRequestHandler`.

Add MKS VNC proxy for VMware

---

nova/conf/mks.py

The old script had a `--verbose` flag that we are using in the k8s deployment definition for all regions. This will include both Xena and older Rocky deployments. The new name of this flag is `--mks-verbose`.
I had previously thought that there still was a global `--verbose` flag I could use, but there was not. This failed the deployment because of the invalid usage of `--verbose`.
Instead of adding an image version check in the helm-chart, create this compatibility flag instead for the duration of the update, and revert this after the Xena upgrade is through everywhere.

mks-proxy: Add compat --verbose flag

---

nova/virt/vmwareapi/cluster_util.py

Introduced in 'vmware: Restart BigVMs with "high" priority', the function "update_cluster_das_vm_override()" did not work, because it created a "ClusterDasVmConfigInfo" instead of a "ClusterDasVmConfigSpec" object. This lead to us not being able to spawn BigVMs with the following error:
Exception in ReconfigureComputeResource_Task.
Cause: Type not found: 'operation'
Change-Id: If9acf9ee07e373b7b24c14c642d0d99fe2a41db1

vmware: Fix update_cluster_das_vm_override

---

nova/virt/vmwareapi/cluster_util.py

Introduced in 'vmware: Restart BigVMs with "high" priority', the
function "update_cluster_das_vm_override()" did not work, because it
created a "ClusterDasVmConfigInfo" instead of a "ClusterDasVmConfigSpec"
object. This lead to us not being able to spawn BigVMs with the
following error:
Exception in ReconfigureComputeResource_Task.
Cause: Type not found: 'operation'
Change-Id: If9acf9ee07e373b7b24c14c642d0d99fe2a41db1

vmware: Fix update_cluster_das_vm_override (for Xena)

---

nova/virt/vmwareapi/vmops.py

Was removed in
f3cc311 "vmware: Remove vestigial nova-network support"
but not taken into account by
aba0dbb "VMware: Image as VM template".

vmware: Remove get_vif_info() is_neutron param usage

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Adding an override for restartPriority when one alrady exists is an error in the VMware API. We do the override twice when running `finish_migration()` during resize toward HANA flavors, once in `_resize()` and once again explicitly. Remove the explicit `set_restart_priority_if_needed()` call.
Fixes f157f63707 'vmware: Restart BigVMs with "high" priority'.

vmware: Fix double restartPriority override

---

nova/api/openstack/compute/views/limits.py

In
daeeafd "baremetal quota handling"
the `_build_per_flavor_limits()` method is incorrectly rewritten to match surrounding code, esp. `_build_absolute_limits()`, and uses not only the limit, but limit and in_use as value for the resulting limit dict.
The original commit,
16857ed "reintroduce baremetal quota handling"
used `absolute_limits` directly as method parameter.

limits: Fix per-flavor limit API value type

---

nova/virt/vmwareapi/volumeops.py

For historic reasons, there is a mapping between
the volume-uuid and the device[].backing.uuid in vmware through extraConfig.
In most cases they are the same, but sometimes they are not.
And apparently, the extraProperties can even hold
wrong information.
Since the risk of a collision of uuids is quite low, and lookup is the iteration over a small list of volumes we first try it that way, avoiding possibly incorrect information in the extraConfig.
Failing that, we still do the additional api call
to get the mapping, and try that.
Change-Id: Ifcdf96cfc6d00473299c1f2a7cb9d23d03294027

[vmwareapi] Look up vmdk volume by uuid directly first

---

nova/virt/ironic/driver.py

The ironic-python-agent uses qemu-img to convert
various image formats to the raw disk format.
QCow2 is already correctly marked accordingly,
but vmdk was missing
Change-Id: Ifd868e6951452b291184bd848d4244d37649f1ed

[ironic] IPA imports VMDKs via qemu-img just fine

---

nova/virt/vmwareapi/images.py

Otherwise will try and decode as UTF-8-encoded text during read().

vmware: Read iso file in binary mode during upload

---

nova/virt/libvirt/driver.py

The code assumes that the libvirt version reported by the hypervisor matches the version of the python library installed. Since we run the agent in a container, that is not correct, and the attribute will not be in the library as it has been build for an older version.
Change-Id: I156047b1f9829a49b429d51ca7f7777606b10a56

[SAP] Workaround libvirt version mismatch

---

nova/cmd/manage.py

Porting #355 onto xena.
This command detects changes in the flavors and syncs the instances flavor-info with the new changes.
`nova-manage sap sync_instances_flavor`

[xena] nova-manage: add sync_instances_flavor command

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

The vcenter doesn't like a reconfiguration call with an empty spec, and raises an error. So we skip that and save ourselves from doing some work on top.
Change-Id: I1da3309500a2cd384c5d7cd431e71297ef5d5a3a

vmware: Do not reconfigure vm without nics in finsh_migration

---

nova/bigvm/manager.py
nova/objects/compute_node.py

- bigvm: Fix ResourceRequest._add_resource() usage
- bigvm/ComputeNodeList: Only get non-deleted nodes
- bigvm: Use public SchedulerReportClient.get_provider_traits
- bigvm: Catch possible KeyError from get_inventory
- bigvm: Replace removed _update_inventory() call

Fix BigVM xena issues

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Adding an override for restartPriority when one alrady exists is an error in the VMware API. We do the override twice when running `finish_migration()` during resize toward HANA flavors, once in `_resize()` and once again explicitly. Remove the explicit `set_restart_priority_if_needed()` call.
Fixes f157f63707 'vmware: Restart BigVMs with "high" priority'.

vmware: Fix double restartPriority override - Xena version

---

nova/compute/monitors/compute_node/vmware_monitor.py

Removed in
eee57f2380 trivial: Remove remaining '_LE' instances
Change-Id: Iea5356d42934f855449d300654771792d07a41fb

vmware-monitor: remove _LE from forward port

---

nova/bigvm/manager.py

In
f534495 Make get_allocations_for_resource_provider raise
`get_allocations_for_resource_provider()` was changed to return a named
tuple with one key "allocations" instead of a dict directly. Unpack
this before iterating over the allocations during cleanup of consumed
providers in the bigvm manager.
Change-Id: I71f0324395e0135d8facdbf45c74c9682093104d

bigvm: Fix allocations dict access during cleanup

---

nova/virt/vmwareapi/vmops.py

The method was refactored and doesn't take resource provider name anymore.
Change-Id: I840e5d671c3df24cd01952b522288982ddfde80e

bigvm: Fix call to set_inventory_for_provider()

---

nova/virt/vmwareapi/vmops.py

We encountered inventory generation conflicts during bigvm spawning, and now do an additional inventory refresh after completing initial spawning.
Change-Id: I65c2be9781b60e31d9a6c6dd84a02c7fe4aa1e72

bigvm: Refresh RP inventory after spawning

---

nova/conf/vmware.py
nova/virt/vmwareapi/driver.py

Since the VMware driver manages multiple datastores in its cluster, it reports the DISK_GB resource "total" as the sum of free space of all of these datastores. The "max_unit" for DISK_GB is computed as the maximum of free space on any of these datastores.
Since the free space on the datastores changes every time a VM gets deployed and deleted and when sDRS moves a disk from one datastore to another, there are a lot of updates happening against Placement - some of which failing, as they are happening in parallel during updating the resource when deleting VMs in parallel.
We try to work around this problem by reducing the necessary updates through limiting the reported "max_unit" to a static value. The limit can be set via config option "resource_disk_gb_max_unit_limit", which is by …

vmware: Optionally limit max_unit for DISK_GB resource

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

VMware by default enables a "quickBoot" feature for efi-booted VMs, which exposes only the first disk of the VM when finding out which disk to boot from. This leads to the VM not booting the rescue disk and thus ignoring the explicitly set "bootOptions.bootOrder" property.
There's an advanced setting called "efi.quickBoot.enabled" to disable the default behavior by providing a value of "FALSE". We set this property on rescue and unset it on unrescue, as it might have an adverse effect on the boot time when the underlying disks are slow.
Change-Id: I64cf1cd4478a9c48a4cce723d224dac31edf85c6
---
I haven't run the tests, yet, as I want the PR to do that.

vmware: Fix rescue for efi-booted VMs

---

nova/api/openstack/compute/hypervisors.py
nova/conf/api.py

The "uptime" field in the hypervisor-details API is
- costly
- not supported for every hypervisor (notably not ironic & vmware)
- noisy in error tracing tools
Introduce a "disable_hypervisor_uptime_detail" setting (default off)
to always return None without asking the compute services.
Change-Id: I544c62af23c98da8cab198d3be1c951645c19ce9

Conditionally disable hypervisor uptime in details API

---

nova/virt/vmwareapi/images.py

The `finally` clause tries to destroy the `task_collector` instance, which might not have been created at all of the `_call_method()` call raised an exception.
This is a fixup for commit 54c437984ba032ad9cc65b7b066a96afaed195fa "Merge clone vm and glance parallel image import".
Change-Id: I5e4bee5f0326185a9b85f361695c941a7d813419

Fix UnboundLocalError in _wait_for_import_task()

---

nova/cmd/manage.py

When using --max-count to limit the amount of instances to change, no instance might be changed at all even though there are instance in need of change. This comes from the fact that we counted all instances, no matter if they have outdated flavor info or not.
To fix this, we now return whether the instance needs fixing from `_update_instance_flavor()` and only count those instances in need of fixing.
Change-Id: I45687c0fbf82e1b229df7e576a60e8540564db35

nova-manage: Count affected instances only

---

nova/conductor/manager.py

We used the wrong variable and thus did not pass on the scheduler_hints set by `nova-compute.api` during the preparation of a resize in `nova-conductor`.
We rename the local variable `scheduler_hints` to `new_scheduler_hints` to make sure we don't make the same mistake again.
This is a fixup for Id80bfd2f3e4771856cc0d85bc1b85a7d14f3b136
Change-Id: I8274ba6b2a4fb0e32b0880939ce50096672bbd3b

Fix passing scheduler_hints on resize

---

nova/virt/vmwareapi/host.py

Other parts of the code expect the capacity to be bigger or equal to the free space, and validate that.
Since the vmwareapi reports sometimes more free space than capacity, we need to limit it
Change-Id: I8b3b39c456596f96718088e7478ff5264a1789cf

vmwareapi: Limit reported free space by capacity

---

custom-requirements.txt

We used it in the shellinaboxproxy, which was dropped with the change I4bb869932ee458120931868bfbceaa99a9ee641d So, we might as well drop the dependency as well.
Change-Id: Ia56516909fccea6bd228a3e1040c1e730704ab21

Drop unused mitmproxy

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Since BIOS-booted VMs cannot boot more than 128 vCPUs, we prevent resizing to such a flavor. Before this patch, the VM would resize, but then not power on.
Change-Id: Ied76457dbfef9b72c11163f1ba9c5a5a73955ca1

vmware: Prevent resize of BIOS VM to > 128 vCPUs

---

nova/virt/vmwareapi/vmops.py

Cross-cluster vMotion creates DRS rules in the target cluster, if the VM was part of them in the source cluster. This can create duplicate DRS rules (by name), as it seems VMware looks at the UUID of the rule not the name.
Since multiple rules for the same VM cannot be enabled at the same time and `cluster_util.get_rule()` only returns the first matching rule, Nova might update the wrong rule and the anti-affinity might not actually work.
To fix this, we get all the rules with the same name during `_update_rule()` to check for duplicates. We keep the first rule we find and delete all others. If the rule is disabled, Nova will enable it already.
Change-Id: Ie5958a1645e8133f303e386353526ec83e646882

vmware: Delete duplicate DRS rules

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Power-on is the very last step of a resize/migration. Failing at this point would leave a VM in a quite inconsistent state in the DB and in the vCenter.
In case power-on fails, we log an error and let nova continue putting the vm into VERIFY_RESIZE state. One can then manually attempt to power-on the VM or revert the resize.
Change-Id: Ic979ce5d7eaf478e5130182a656996cc5f1af29a

allow power-on to fail on finish_resize

---

nova/bigvm/manager.py

With Nova-Xena automatically adding the COMPUTE_STATUS_DISABLED trait
to nodes whose compute-service is disabled, we can and should ignore
those nodes, when looking for a new bigvm cluster.
Change-Id: I57cad032fc9002cb4b5013e4868215a60ebe412a

bigvm: Ignore disabled compute nodes

---

nova/scheduler/filters/shard_filter.py
nova/scheduler/mixins.py
nova/tests/unit/scheduler/filters/test_shard_filter.py

We have an implementation caching certain tags for projects in the `ShardFilter`. In the future, we want to add another filter to the scheduler that will also react to project tags. Therefore, we move the code handling the caching out into a Mixin class.
The Mixin supports prefix and exact matching, configured via class attribute.
Change-Id: I3ad865ec4dbbf097fc4718b0753b86a8e64775fa

scheduler: Move project tag caching to mixin

---

nova/conf/scheduler.py
nova/scheduler/filters/volume_size_same_shard_resize_filter.py
nova/tests/unit/scheduler/filters/test_volume_size_same_shard_resize_filter.py

We want to allow customers to optionally disable resizes of VMs across shards if the sum of the volume sizes reach a certain threshold. With this, we want customers to have more reliable resize times that might fit in their downtime windows as resizing across shards can create volume migrations which can take a long time.
The threshold is not configurable by the user and set to 1 TiB by default.  It can be changed with the
`volume_size_same_shard_resize_filter_sum` config setting.
Change-Id: I13a0e16713b90954cb48ea7f0a7c6db870d60bdc

scheduler: Add VolumeSizeSameShardResizeFilter

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/driver.py
nova/virt/vmwareapi/vmops.py

Each caller to get properties for an instance goes through either _get_instance_props or _get_instance_properties That ensures, that everywhere the ManagedObjectNotFound exception is handled and raising an InstanceNotFound instead, which is understood by the compute manager
Change-Id: If5c62a7257eab99ea7f4ed5638261948aed85455

Vmware: Consolidate getting properties for instances

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

There can be VMs where the image inflated to more than the flavor's root disk. Since VMware doesn't allow shrinking a disk, these VMs cannot be resized - and can also not be offline migrated, as that's the same code path.
Since an offline migration can only be triggered by admins and is done e.g. during decommissioning a host, we now allow offline migration with too big root disks. Otherwise, such a VM would always require customer interaction to get it removed or special care by booting into BIOS and live-migrating it.
We have to change `migrate_disk_and_power_off()` and not `finish_migration()`, because the latter does not check disk size differences but rather relies on the `resize_instance` argument passed in from `nova.compute.manager`. `resize_instance` can only be `True` if the …

vmware: Allow offline migration with too big root disk

---

nova/virt/vmwareapi/driver.py

When a VM moves away from a compute node, the MOref cache in
nova.virt.vmwareapi.vm_util._VM_REFS_CACHE is not cleaned up.
If the VM is then migrated back to the same node it once came from,
_and_ it has volumes attached, the attachment creation fails in the
VCenter API, because the MOref used is the stale one.
Clean up the cache after moving away, so that if the VM comes back,
the new MOref value is fetched and volume attachments work.
Change-Id: Ib1f4b7cdd8c28924b674032a9ea92171b796bdb9

vmware: Clear MOref cache on source after migration

---

nova/compute/api.py
nova/compute/instance_actions.py
nova/virt/vmwareapi/driver.py

To be able to use the customer API for triggering an in-cluster vMotion properly, one has to be able to see if the vMotion worked out. To be able to report the status, we add an instance action `in_cluster_vmotion` with a single expected event coming from the `vmwareapi` driver.
Change-Id: I619d86ee4e7b7c84107c9083b629c377d04534f8

Add instance-action in_cluster_vmotion

---

nova/scheduler/weights/hv_ram_class.py
nova/tests/unit/scheduler/weights/test_weights_hv_ram_class.py

The config comes in as strings and we multiplied that string by 1024 instead of first converting it to int and then multiplying by 1024 to make it MiB.
Change-Id: I6f3a06303652e1160e990b2f9574ef5dbbf198f1
fixup-for: Ia042e466544b73b8dd15ee7231d3baf1da6069a1

[scheduler] Fix HvRamClassWeigher config loading

---

nova/virt/vmwareapi/cluster_util.py
nova/virt/vmwareapi/vmops.py

The restart-priority migrates with the VM. Re-setting it raises the error
InvalidDasConfigArgument: "The setting of vmConfig is invalid for cluster ..."
So check if the setting is present before setting it.
fixup: 89c95963f551 vmware: Restart BigVMs with "high" priority
Change-Id: Ibccec024af231a69ffcfa87f9575830f176e6a8c

vmware: Set restart-priority only if not present

---

nova/objects/flavor.py
nova/objects/instance.py

There are more use-cases than baremetal flavors that use "quota:separate" in their extra_specs: big VMs. Therefore, we rename the "baremetal" to "separate" in this context.
Change-Id: I4b9f97246af9dad6574569deed6c1d1fcd72cbda

quota: Rename "baremetal" to "separate"

---

nova/tests/unit/virt/vmwareapi/test_volumeops.py
nova/virt/vmwareapi/volumeops.py

- Skip FCD type volumes and don't try to delete the shadow vm: 
The fcd implementation lookups volumes from a catalog using 2 identifiers fcd_id and ds_mo_ref, so no shadowvm are present for this kind of volumes, and so the deletion would run into exception due to non-existing shadowvm ....
- Fix/simplify fcd detach:
If a cinder volume gets relocated to a different datastore, the connection_info cached in the bdm is still referring the old ds, so the lookup of fcd_obj fails due to the out-of-date ds_mo_ref. Even in migration the volume_id stays a stable id, so this fix is just lookups the volume using the volume_id on the backing.uuid instead of lookup of fcd_obj to figure out the vmdk_path The terminate_connection to cinder does not result a refreshed connection_info, and calling the …

FCD related fixes

---

nova/objects/flavor.py
nova/objects/instance.py

Instead of returning "instances_$FLAVOR_NAME" during finding the instance types during quota counting we only return the actual flavor name. There are (currently) three different places that return instance type data. Having the generation of "instances_$FLAVOR_NAME" in a single place seems better. Additionally, the attribute "name" returned by the three places does not reflect that it contains the "separate" name and not the instance type name.
Change-Id: Idc007bea83f9198783dcd1af2d53d8934f28ede1

quota: Build instances_$FLAVOR_NAME in a single place

---

nova/virt/vmwareapi/images.py
nova/virt/vmwareapi/vmops.py

There were a lot of occurrences where broken / interrupted image downloads laid out 3.91MiB (4096000 bytes) vmdk files.
We now treat this size as an INVALID_VMDK_SIZE and we delete any cached template VM or vmdk file having that size.
Change-Id: Id2cded69fd88f2d208dcb3421d5744f6291856a2

[vmware] delete template VMs with invalid size

---

nova/api/openstack/compute/quota_classes.py
nova/quota.py
nova/tests/unit/test_quota.py

Please see the individual commits for details.

quota: Add SAPQuotaEngine and SAPCustomResource

---

nova/virt/vmwareapi/vmops.py

> 'dict_values' object has no attribute 'get'
Fixup-for: I907278b970d5ac658223e821b46461eeac2a5275
Change-Id: I10df0902ea6ff27d1d32d20bf6c6d8c597184e22

vmware: Fix CPU reservation host-stats access

---

nova/objects/quotas.py

In "quota:separate: Fix Quotas.check_deltas()" we changed the code but failed to use the right variables so it created a `KeyError` afterwards if the resource was not used by the project, yet.
Change-Id: I57414cd78343bb26e603628f19e72bbc0fac2984

Fix `Quotas.check_deltas()` after overhaul

---

nova/compute/utils.py

The `usage` kwarg in the `OverQuota` exception does not contain instance-separate usages if it's not used yet.
Change-Id: Ic2bb1e7b9223ca47e1ce944d7bbb711de277e31b

quota: Treat missing instance_* usage key as 0

---

nova/virt/vmwareapi/vm_util.py

Zero MHz will be ignored later in `aggregate_stats_from_cluster()` when calculating the cluster's median MHz value.
Change-Id: Ic06bb756d37e2d552c1b734b8600a6cdc08b3c08

vmware: Default to 0 CPU-MHz with no HW-summary

---

nova/conf/scheduler.py
nova/scheduler/host_manager.py
nova/scheduler/manager.py
nova/scheduler/weights/decommissioning.py
nova/tests/unit/scheduler/weights/test_weights_decommissioning.py

> De-prioritise the hosts which are being decommissioned, by always placing
> them the last in the queue.
> Allow such hosts to be scheduled only when absolutely necessary, i.e.
> when all other hosts are full.
See Individual commit messages

Decommissioning weigher

---

nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

VMware reports CPU resources in MHz, but this is in relation to the
physical CPU count, not the hyperthreaded CPU count. Check for the
pCPU-to-vCPU ratio (which is either 1 = "no hyperthreading",
or 2 = "hyperthreaded") and adjust the per-CPU MHz number of the host.
The code is very defensive: The first division is inverted as to avoid
a second division in the other line. If either `threads` or `pcpus` is
0 then 1 will be substituted so that the ratio will be 1 in the case
of missing or zero stats.
Fixup-for: I907278b970d5ac658223e821b46461eeac2a5275
Change-Id: I5cb406e53b32b71a802a178b5b7c635657779822

vmware: Account for hyperthreading when reserving CPUs

---

nova/api/openstack/compute/sap_admin_api.py
nova/api/validation/extra_specs/quota.py
nova/compute/api.py
nova/compute/utils.py
nova/conf/quota.py
nova/objects/flavor.py
nova/objects/instance.py
nova/policies/sap_admin_api.py
nova/quota.py
nova/tests/unit/scheduler/weights/test_weights_resize_same_host.py
nova/tests/unit/test_policy.py
nova/utils.py

This PR switches from using quota-class-sets to reading the Flavors' extra_specs. It also cleans up some parts belonging to `quota:separate` and `quota:instance_only` in the process.
Since the new information read from `extra_specs` is cached, we also add a custom API to clear the cache.
Please see the individual commits' messages for more information.

Read quota:separate from flavors

---

nova/conf/vmware.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/host.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

We want to be able to stack VMs instead of spreading them (i.e. bin packing), but DRS does not support that.
We implement a simple bin packing algorithm in the vmwareapi driver that choses the fullest host still having enough resources free.
We determine the fullest host by looking at the free memory because this feature will only run on hana-exclusive BBs where we deal with NUMA-aligned VMs, and because we currently don't know the number of vCPUs used within a cluster.
There are 2 conditions for the stacking to happen
1. DRS is set to disabled.
2. [vmware]/drs_disabled_stack_vms is set to True
Change-Id: Icffda14ecc43f6cb6e0d31842ae2e0ca5e513eb3

Schedule big VMs to hosts in DRS-disabled clusters

---

nova/conf/scheduler.py
nova/scheduler/weights/sapphire_rapids.py
nova/tests/unit/scheduler/weights/test_weights_sapphire_rapids.py

This weigher weighs down hosts having the CUSTOM_HW_SAPPHIRE_RAPIDS trait i.e. have sapphire rapids CPUs. We want our general purpose flavors that do not explicitly request sapphire rapids CPUs to land on the older hardware i.e. not sapphire rapids, so they don't fill up the space. We still want the old flavors to be deployable if we run out of space on the old hardware e.g. during decommissioning.
Change-Id: Ie6fff51ebf0da36627f162a9be6a2d7983423ccd

scheduler: Add SapphireRapidsWeigher

---

nova/tests/unit/virt/vmwareapi/test_vm_util.py
nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vm_util.py
nova/virt/vmwareapi/vmops.py

The device order persists, and may refer to another device. That breaks cloning the vm for the purpose of a snapshot, where the disk gets removed.
Squash-into: I64cf1cd4478a9c48a4cce723d224dac31edf85c6
Change-Id: I90d7890f6b10622b7a6efc8e988d7736a3e87df2

vmware: Fix unrescue by resetting boot device order

---

nova/virt/vmwareapi/vmops.py

Even though Nova checks if the VM has VMware tools running, this exception might still occur if the VMware tools stop running in the meantime.
We return False back, so that Nova continues to hard shutdown.
Change-Id: Ida4d6dfd2dab0ad0a382f7c98b69c8326414bdda

vmware: handle the ToolsUnavailableException on power_off

---

nova/scheduler/filters/resize_vcpu_max_unit_filter.py
nova/scheduler/utils.py
nova/tests/unit/scheduler/filters/test_hana_memory_max_unit_filter.py
nova/tests/unit/scheduler/filters/test_resize_vcpu_max_unit_filter.py
nova/tests/unit/scheduler/weights/test_hana_binpack.py
nova/tests/unit/virt/vmwareapi/test_driver_api.py
nova/virt/vmwareapi/driver.py

It seems that `ComputeNode.stats` are converted to string before being stored in the database (it's a `DictOfNullableStringsField`).
Thus, we must convert it to `int` before using it in the filters.
There are multiple fixes in this PR, so please read the individual commit messages.
The fixes are for:
- HANABinPackWeigher
- HANAMemoryMaxUnitFilter
- ResizeVcpuMaxUnitFilter

Fix filters relying on host stats integers

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Resize uses a hard PowerOff to shut down the VM. This can lead to data not being written to disk and thus broken files.
The _soft_shutdown method first attempts to shutdown the OS via the VMware tools, and fall back to the hard PowerOff after the configured `shutdown_timeout` and `compute.shutdown_retry_interval`.
Change-Id: Id2fdeac6355eb7e49f649ba8fa4b48251bb7db61

[vmware] use soft shutdown on the cold resize/migrate

---

nova/conf/scheduler.py
nova/scheduler/weights/aggregate_multitenancy_isolation.py
nova/tests/unit/scheduler/weights/test_weights_aggregate_multitenancy_isolation.py

We want the hardware we dedicate to specific projects through aggregates with `filter_tenant_id` property to be preferred by those projects compared to generally available hosts.
Change-Id: Ide6471a522785f7f4209d5b3640af2a521a05405

scheduler: Add AggregateMultiTenancyIsolation weigher

---

nova/tests/unit/console/test_websocketproxy.py

In response to bug 1927677 we added a workaround to NovaProxyRequestHandler to respond with a 400 Bad Request if an open redirect is attempted:
Ie36401c782f023d1d5f2623732619105dc2cfa24
I95f68be76330ff09e5eabb5ef8dd9a18f5547866
Recently in python 3.10.6, a fix has landed in cpython to respond with a 301 Moved Permanently to a sanitized URL that has had extra leading '/' characters removed.
This breaks our existing unit tests which assume a 400 Bad Request as the only expected response.
This adds handling of a 301 Moved Permanently response and asserts that the redirect location is the expected sanitized URL. Doing this instead of checking for a given python version will enable the tests to continue to work if and when the cpython fix gets backported to older python versions.
While …

Cherry-Pick: Adapt websocketproxy tests for SimpleHTTPServer fix

---

nova/quota.py

The SAPQuotaEngine instance is created as a module variable (nova.quota.QUOTAS), so the CONF might have not been initialized at the point when SAPQuotaEngine.__init__ is called.
Similarily to how the self._driver is initialised, we are now initializing the self._cache client outside of the constructor, making sure the CONF is also initialized at that point.
This fixes the issues where DictCacheBackend was used by the SAPQuotaEngine, instead of the configured Memcached backend.
Change-Id: Iceba3c7820f9c6b9255ef6e00a9f49ed4677c12f

Fix SAPQuotaEngine cache client initialization

---

nova/tests/fixtures/libvirt.py
nova/tests/unit/virt/libvirt/test_driver.py
nova/virt/libvirt/driver.py
nova/virt/libvirt/host.py
releasenotes/notes/use-compareHypervisorCPU-b75c8f097cc73556.yaml

The older libvirt API compareCPU() does not take into account the capabilities of the "host hypervisor" (KVM, QEMU and the details libvirt knows about the host) when comparing CPUs.  This is causing unwanted failures during CPU compatibility checks.  To fix this and other related problems, libvirt has introduced (in v4.4.0) a newer API, compareHypervisorCPU(), which _does_ take into account the host hypervisor's capabilities before comparing CPUs.  This will help fix a range of problems, such as[1][2].
So let's switch to the newer API, which is largely a drop-in replacement.
In this patch:
- Introduce a wrapper method, compare_hypervisor_cpu() for libvirt's compareHypervisorCPU() API.
- Update the _compare_cpu() method to use the wrapper method, compare_hypervisor_cpu().
- Update the unit …

libvirt: Replace usage of compareCPU() with compareHypervisorCPU()

---

nova/conf/workarounds.py
nova/virt/libvirt/config.py
nova/virt/libvirt/driver.py

This is a hacky version of libvirt: Support maxphysaddr, which does it properly over flavor and images,
but needs also a trait upgrade.
Do not port it to later versions.
With Libvirt v8.7.0+, the <maxphysaddr> sub-element of the <cpu> element specifies the number of vCPU
physical address bits [1].
[1] https://libvirt.org/news.html#v8-7-0-2022-09-01
Change-Id: If89f71511c050a494657614b789adcdb80297725

Hack: libvirt: Support maxphysaddr.

---

nova/tests/unit/virt/vmwareapi/test_vmops.py
nova/virt/vmwareapi/vmops.py

Since vSphere 6, VMware supports `webmks` as `ticketType` in addition to `mks`. `webmks` provides the remote console of a VM via WebSocket endpoint and is supposed to be used with their SDK. It does fall back to normal VNC which can be used with e.g. `noVNC` though.
With this change, we can follow-up by removing our custom mks proxy code, as we plan to expose `webmks` via Nginx directly.
Change-Id: I99294d7f6bf0539d20887322eeadb2580297fc8a

vmware: Switch mks console to `webmks`

---

nova/conf/scheduler.py
nova/scheduler/external.py
nova/scheduler/manager.py
nova/tests/unit/scheduler/test_external.py
nova/tests/unit/scheduler/test_manager.py

SAP: Introduce an external scheduler filter
Provides support for an external service that can perform advanced scheduling 
decisions. SchedulerManager now calls a function call_external_scheduler_api
after executing filters and weighers. This function sends the hosts and their
current weights to an external scheduling service. This service then performs
advanced scheduling decisions and returns the sorted list of host names, from
highest priority to lowest priority. To toggle this feature, provide
external_scheduler_api_url to Nova's configuration.

SAP: Introduce external scheduler filter

---

nova/scheduler/external.py

Fixes an AttributeError when calling the external scheduler.

Remove host state from external scheduler request

---

nova/conf/libvirt.py
nova/tests/unit/virt/libvirt/test_config.py
nova/tests/unit/virt/libvirt/test_driver.py
nova/virt/libvirt/config.py
nova/virt/libvirt/driver.py

At SAP we use the chassis asset tag within the SMBIOS sysinfo structure to track billing. This PR allows configuring the tag in libvirt like [how it's configured in VMWare](https://github.com/sapcc/nova/blob/e446e928429ecb52abb945922ac37bb1cfa7be38/nova/conf/vmware.py#L424>).
This PR is one part of the fix for ["setting chassis_asset_tag to 'SAP CCloud VM' for KVM vms"](<https://github.com/cobaltcore-dev/cobaltcore/issues/37>).

libvirt: Make SMBIOS Chassis Asset tag configurable
